=== willwade/DasherCoreRust/data/settings/settings.dtd
<?xml version="1.0" encoding="utf-8"?>
<!ELEMENT settings ((long|bool|string)*)>

<!ELEMENT long EMPTY>
<!ATTLIST long name  CDATA #REQUIRED>
<!ATTLIST long value CDATA #REQUIRED>


<!ELEMENT bool EMPTY>
<!ATTLIST bool name  CDATA #REQUIRED>
<!ATTLIST bool value CDATA #REQUIRED>

<!ELEMENT string EMPTY>
<!ATTLIST string name  CDATA #REQUIRED>
<!ATTLIST string value CDATA #REQUIRED>

=== willwade/DasherCoreRust/data/settings/settings.direct.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE settings SYSTEM "settings.dtd">
<settings>
<long name="AppStyle" value="2"/>
<bool name="ConfirmUnsavedFiles" value="False"/>
<bool name="ControlMode" value="False"/>
<bool name="CopyOnStop" value="False"/>
<bool name="TimeStampNewFiles" value="False"/>
  <string name="ControlBoxID" value="Direct Entry (ascii)"/>
  <string name="ToolbarID" value="Direct Entry"/>
</settings>

=== willwade/DasherCoreRust/data/settings/settings.edit.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE settings SYSTEM "settings.dtd">
<settings>
<long name="AppStyle" value="1"/>
<bool name="ConfirmUnsavedFiles" value="True"/>
<bool name="ControlMode" value="True"/>
<bool name="CopyOnStop" value="True"/>
<bool name="FullScreen" value="True"/>
<bool name="TimeStampNewFiles" value="True"/>
<string name="ControlBoxID" value="Edit Larger Document (ascii)"/>
<string name="ToolbarID" value="Edit Larger Document"/>
</settings>

=== willwade/DasherCoreRust/data/settings/settings.speak.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE settings SYSTEM "settings.dtd">
<settings>
<long name="AppStyle" value="0"/>
<long name="EditFontSize" value="20"/>
<long name="EditHeight" value="200"/>
<bool name="ConfirmUnsavedFiles" value="False"/>
<bool name="ControlMode" value="True"/>
<bool name="CopyOnStop" value="True"/>
<bool name="FullScreen" value="True"/>
<bool name="TimeStampNewFiles" value="False"/>
<string name="ControlBoxID" value="Conversation (ascii)"/>
<string name="ToolbarID" value="Conversation"/>
</settings>
