=== willwade/DasherCoreRust/data/colours/color.dtd
<!-- Color schemes contain defintions of colors to be used by Dasher -->
<!ELEMENT colors (groupColorInfo*)>
<!ATTLIST colors name CDATA #REQUIRED> <!-- Name of the ColorSchema -->
<!ATTLIST colors parentName CDATA "Default"> <!-- Parent ColorSchema from which missing data is inherited -->

<!-- Special Colors that are used in various places in Dasher Rendering -->
<!ATTLIST colors
    backgroundColor CDATA #IMPLIED
    crosshairColor CDATA #IMPLIED
    inputLineColor CDATA #IMPLIED
    inputPositionColor CDATA #IMPLIED
    rootNodeColor CDATA #IMPLIED
    defaultOutlineColor CDATA #IMPLIED
    defaultLabelColor CDATA #IMPLIED
    selectionHighlightColor CDATA #IMPLIED
    selectionInactiveColor CDATA #IMPLIED
    circleOutlineColor CDATA #IMPLIED
    circleStoppedColor CDATA #IMPLIED
    circleWaitingColor CDATA #IMPLIED
    circleStartedColor CDATA #IMPLIED
    firstStartBoxColor CDATA #IMPLIED
    secondStartBoxColor CDATA #IMPLIED
    twoPushDynamicActiveMarkerColor CDATA #IMPLIED
    twoPushDynamicInactiveMarkerColor CDATA #IMPLIED
    twoPushDynamicOuterGuidesColor CDATA #IMPLIED
    infoTextColor CDATA #IMPLIED
    infoTextBackgroundColor CDATA #IMPLIED
    warningTextColor CDATA #IMPLIED
    warningTextBackgroundColor CDATA #IMPLIED
    gameGuideColor CDATA #IMPLIED
    oneButtonDynamicOuterGuidesColor CDATA #IMPLIED
    conversionNodeColor CDATA #IMPLIED
>

<!-- Group Color Definition -->
<!ELEMENT groupColorInfo EMPTY>
<!ATTLIST groupColorInfo name CDATA #REQUIRED> <!-- Name of the Group that is referenced by the alphabet -->
<!ATTLIST groupColorInfo groupColor CDATA #IMPLIED> <!-- Color of the group itself -->
<!ATTLIST groupColorInfo altGroupColor CDATA #IMPLIED>
<!ATTLIST groupColorInfo groupOutlineColor CDATA #IMPLIED> <!-- OutlineColor of the group itself -->
<!ATTLIST groupColorInfo altGroupOutlineColor CDATA #IMPLIED>
<!ATTLIST groupColorInfo groupLabelColor CDATA #IMPLIED> <!-- LabelColor of the group itself -->
<!ATTLIST groupColorInfo altGroupLabelColor CDATA #IMPLIED>
 <!-- Sequence colors that are split and iterated in Dasher to cover the whole alphabet.
    A sequence is defined by a list of hex color values separated by commas.
    Example: nodeColorSequence="#B4DAA2FF,#BEEEBEFF" -->
<!ATTLIST groupColorInfo
    nodeColorSequence CDATA #IMPLIED
    altNodeColorSequence CDATA #IMPLIED
    nodeOutlineColorSequence CDATA #IMPLIED
    altNodeOutlineColorSequence CDATA #IMPLIED
    nodeLabelColorSequence CDATA #IMPLIED
    altNodeLabelColorSequence CDATA #IMPLIED
>

=== willwade/DasherCoreRust/data/colors/color.europeanasian.for.colourblind.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE colors SYSTEM "color.dtd">
<colors name="European/Asian for Colourblind" parentName="Default" firstStartBoxColor="#ff9a9a" secondStartBoxColor="#ffd2d2" twoPushDynamicInactiveMarkerColor="#ffc888" twoPushDynamicOuterGuidesColor="#fff082" conversionNodeColor="#f5f5f5">
	<groupColorInfo name="lowercase" nodeColorSequence="#00ffff,#b4eeb4,#9bcd9b,#00ffff,#b4eeb4,#9bcd9b,#00ffff,#b4eeb4,#9bcd9b,#00ffff,#b4eeb4,#9bcd9b,#00ffff,#b4eeb4,#9bcd9b,#00ffff,#b4eeb4,#9bcd9b,#00ffff,#b4eeb4,#9bcd9b,#00ffff,#b4eeb4,#9bcd9b,#00ffff,#b4eeb4,#9bcd9b,#00ffff,#b4eeb4,#9bcd9b" altNodeColorSequence="#87ceff,#ffaeb9,#ffc888,#87ceff,#ffaeb9,#ffc888,#87ceff,#ffaeb9,#ffc888,#87ceff,#ffaeb9,#ffc888,#87ceff,#ffaeb9,#ffc888,#87ceff,#ffaeb9,#ffc888,#87ceff,#ffaeb9,#ffc888,#87ceff,#ffaeb9,#ffc888,#87ceff,#ffaeb9,#ffc888,#87ceff,#ffaeb9,#ffc888" />
	<groupColorInfo name="lowercaseBackground" groupColor="#dcdcdc" groupOutlineColor="#dadada" nodeColorSequence="#00ffff,#b4eeb4,#9bcd9b,#00ffff,#b4eeb4,#9bcd9b,#00ffff,#b4eeb4,#9bcd9b,#00ffff,#b4eeb4,#9bcd9b,#00ffff,#b4eeb4,#9bcd9b,#00ffff,#b4eeb4,#9bcd9b,#00ffff,#b4eeb4,#9bcd9b,#00ffff,#b4eeb4,#9bcd9b,#00ffff,#b4eeb4,#9bcd9b,#00ffff,#b4eeb4,#9bcd9b" altNodeColorSequence="#87ceff,#ffaeb9,#ffc888,#87ceff,#ffaeb9,#ffc888,#87ceff,#ffaeb9,#ffc888,#87ceff,#ffaeb9,#ffc888,#87ceff,#ffaeb9,#ffc888,#87ceff,#ffaeb9,#ffc888,#87ceff,#ffaeb9,#ffc888,#87ceff,#ffaeb9,#ffc888,#87ceff,#ffaeb9,#ffc888,#87ceff,#ffaeb9,#ffc888" />
	<groupColorInfo name="uppercase" groupColor="#ffff00" groupOutlineColor="#dadada" nodeColorSequence="#00ffff,#b4eeb4,#9bcd9b,#00ffff,#b4eeb4,#9bcd9b,#00ffff,#b4eeb4,#9bcd9b,#00ffff,#b4eeb4,#9bcd9b,#00ffff,#b4eeb4,#9bcd9b,#00ffff,#b4eeb4,#9bcd9b,#00ffff,#b4eeb4,#9bcd9b,#00ffff,#b4eeb4,#9bcd9b,#00ffff,#b4eeb4,#9bcd9b,#00ffff,#b4eeb4" altNodeColorSequence="#87ceff,#ffaeb9,#ffc888,#87ceff,#ffaeb9,#ffc888,#87ceff,#ffaeb9,#ffc888,#87ceff,#ffaeb9,#ffc888,#87ceff,#ffaeb9,#ffc888,#87ceff,#ffaeb9,#ffc888,#87ceff,#ffaeb9,#ffc888,#87ceff,#ffaeb9,#ffc888,#87ceff,#ffaeb9,#ffc888,#87ceff,#ffaeb9" />
	<groupColorInfo name="punctuation" groupColor="#00c800" groupOutlineColor="#dadada" nodeColorSequence="#ff91ff,#729acc,#c8e4f3,#8eacde,#c8e4f3" altNodeColorSequence="#ff91ff,#729acc,#c8e4f3,#8eacde,#c8e4f3" />
	<groupColorInfo name="limitedPunctuation" groupColor="#00c800" groupOutlineColor="#dadada" nodeColorSequence="#dcdcdc,#ffb6ff,#ff91ff,#729acc,#c8e4f3,#8eacde,#c8e4f3" altNodeColorSequence="#dcdcdc,#ffb6ff,#ff91ff,#729acc,#c8e4f3,#8eacde,#c8e4f3" />
	<groupColorInfo name="punctuationLong" groupColor="#00c800" groupOutlineColor="#dadada" nodeColorSequence="#ffacac,#ff8484,#ffc0c0,#ff9a9a,#ffd2d2,#aaaaaa,#787878,#c3c3c3,#919191,#dcdcdc,#aaaaaa,#787878,#c3c3c3,#919191,#ff91ff,#ff52ff,#ffa2ff,#ff80ff,#ffb6ff,#ff91ff,#ff52ff,#ffa2ff,#ff80ff,#ffb6ff,#ff52ff,#ffa2ff,#ff80ff,#ffb6ff,#ff91ff,#f5f5f5,#8eacde,#6e82bc,#aac8e8,#729acc,#c8e4f3,#8eacde,#c8e4f3" altNodeColorSequence="#ffacac,#ff8484,#ffc0c0,#ff9a9a,#ffd2d2,#aaaaaa,#787878,#c3c3c3,#919191,#dcdcdc,#aaaaaa,#787878,#c3c3c3,#919191,#ff91ff,#ff52ff,#ffa2ff,#ff80ff,#ffb6ff,#ff91ff,#ff52ff,#ffa2ff,#ff80ff,#ffb6ff,#ff52ff,#ffa2ff,#ff80ff,#ffb6ff,#ff91ff,#ffffff,#8eacde,#6e82bc,#aac8e8,#729acc,#c8e4f3,#8eacde,#c8e4f3" />
	<groupColorInfo name="numbers" groupColor="#ff0000" groupOutlineColor="#dadada" nodeColorSequence="#ffacac,#ff8484,#ffc0c0,#ff9a9a,#ffd2d2" altNodeColorSequence="#ffacac,#ff8484,#ffc0c0,#ff9a9a,#ffd2d2" />
	<groupColorInfo name="accents" groupColor="#00c800" groupOutlineColor="#dadada" nodeColorSequence="#ffe600,#ffe66e" altNodeColorSequence="#ffe600,#ffe66e" />
	<groupColorInfo name="space" nodeColorSequence="#f5f5f5" />
	<groupColorInfo name="paragraph" nodeColorSequence="#f5f5f5" />
	<groupColorInfo name="paragraphSpace" nodeColorSequence="#f5f5f5,#f5f5f5" />
</colors>

=== willwade/DasherCoreRust/data/colors/color.thai.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE colors SYSTEM "color.dtd">
<colors name="Thai" parentName="Default" firstStartBoxColor="#ff9a9a" secondStartBoxColor="#ffd2d2" twoPushDynamicInactiveMarkerColor="#ffc888" twoPushDynamicOuterGuidesColor="#fff082">
	<groupColorInfo name="lowercase" nodeColorSequence="#ffbbff,#c8e4f3,#aac8e8,#ffaeb9,#ffd2d2,#ff9a9a,#ffaeb9,#ffbbff,#c8e4f3,#ffaeb9,#ffd2d2,#ff9a9a,#ffaeb9,#ffbbff,#ff80ff,#c8e4f3,#ffaeb9,#ffd2d2,#ff9a9a,#ffbbff,#ff80ff,#c8e4f3,#ffaeb9,#ffd2d2,#ff9a9a,#ffbbff,#ff80ff,#c8e4f3,#aac8e8,#ffaeb9" altNodeColorSequence="#ffbbff,#c8e4f3,#aac8e8,#ffaeb9,#ffd2d2,#ff9a9a,#ffaeb9,#ffbbff,#c8e4f3,#ffaeb9,#ffd2d2,#ff9a9a,#ffaeb9,#ffbbff,#ff80ff,#c8e4f3,#ffaeb9,#ffd2d2,#ff9a9a,#ffbbff,#ff80ff,#c8e4f3,#ffaeb9,#ffd2d2,#ff9a9a,#ffbbff,#ff80ff,#c8e4f3,#aac8e8,#ffaeb9" />
	<groupColorInfo name="lowercaseBackground" groupColor="#dcdcdc" groupOutlineColor="#dadada" nodeColorSequence="#ffbbff,#c8e4f3,#aac8e8,#ffaeb9,#ffd2d2,#ff9a9a,#ffaeb9,#ffbbff,#c8e4f3,#ffaeb9,#ffd2d2,#ff9a9a,#ffaeb9,#ffbbff,#ff80ff,#c8e4f3,#ffaeb9,#ffd2d2,#ff9a9a,#ffbbff,#ff80ff,#c8e4f3,#ffaeb9,#ffd2d2,#ff9a9a,#ffbbff,#ff80ff,#c8e4f3,#aac8e8,#ffaeb9" altNodeColorSequence="#ffbbff,#c8e4f3,#aac8e8,#ffaeb9,#ffd2d2,#ff9a9a,#ffaeb9,#ffbbff,#c8e4f3,#ffaeb9,#ffd2d2,#ff9a9a,#ffaeb9,#ffbbff,#ff80ff,#c8e4f3,#ffaeb9,#ffd2d2,#ff9a9a,#ffbbff,#ff80ff,#c8e4f3,#ffaeb9,#ffd2d2,#ff9a9a,#ffbbff,#ff80ff,#c8e4f3,#aac8e8,#ffaeb9" />
	<groupColorInfo name="uppercase" groupColor="#ffff00" groupOutlineColor="#dadada" nodeColorSequence="#ffbbff,#c8e4f3,#aac8e8,#ffaeb9,#ffd2d2,#ff9a9a,#ffaeb9,#ffbbff,#c8e4f3,#ffaeb9,#ffd2d2,#ff9a9a,#ffaeb9,#ffbbff,#ff80ff,#c8e4f3,#ffaeb9,#ffd2d2,#ff9a9a,#ffbbff,#ff80ff,#c8e4f3,#ffaeb9,#ffd2d2,#ff9a9a,#ffbbff,#ff80ff,#c8e4f3,#aac8e8" altNodeColorSequence="#ffbbff,#c8e4f3,#aac8e8,#ffaeb9,#ffd2d2,#ff9a9a,#ffaeb9,#ffbbff,#c8e4f3,#ffaeb9,#ffd2d2,#ff9a9a,#ffaeb9,#ffbbff,#ff80ff,#c8e4f3,#ffaeb9,#ffd2d2,#ff9a9a,#ffbbff,#ff80ff,#c8e4f3,#ffaeb9,#ffd2d2,#ff9a9a,#ffbbff,#ff80ff,#c8e4f3,#aac8e8" />
	<groupColorInfo name="punctuation" groupColor="#00c800" groupOutlineColor="#dadada" nodeColorSequence="#ff91ff,#729acc,#c8e4f3,#8eacde,#c8e4f3" altNodeColorSequence="#ff91ff,#729acc,#c8e4f3,#8eacde,#c8e4f3" />
	<groupColorInfo name="limitedPunctuation" groupColor="#00c800" groupOutlineColor="#dadada" nodeColorSequence="#dcdcdc,#ffb6ff,#ff91ff,#729acc,#c8e4f3,#8eacde,#c8e4f3" altNodeColorSequence="#dcdcdc,#ffb6ff,#ff91ff,#729acc,#c8e4f3,#8eacde,#c8e4f3" />
	<groupColorInfo name="punctuationLong" groupColor="#00c800" groupOutlineColor="#dadada" nodeColorSequence="#ffacac,#ff8484,#ffc0c0,#ff9a9a,#ffd2d2,#aaaaaa,#787878,#c3c3c3,#919191,#dcdcdc,#aaaaaa,#787878,#c3c3c3,#919191,#ff91ff,#ff52ff,#ffa2ff,#ff80ff,#ffb6ff,#ff91ff,#ff52ff,#ffa2ff,#ff80ff,#ffb6ff,#ff52ff,#ffa2ff,#ff80ff,#ffb6ff,#ff91ff,#ebebeb,#8eacde,#6e82bc,#aac8e8,#729acc,#c8e4f3,#8eacde,#c8e4f3" altNodeColorSequence="#ffacac,#ff8484,#ffc0c0,#ff9a9a,#ffd2d2,#aaaaaa,#787878,#c3c3c3,#919191,#dcdcdc,#aaaaaa,#787878,#c3c3c3,#919191,#ff91ff,#ff52ff,#ffa2ff,#ff80ff,#ffb6ff,#ff91ff,#ff52ff,#ffa2ff,#ff80ff,#ffb6ff,#ff52ff,#ffa2ff,#ff80ff,#ffb6ff,#ff91ff,#ffffff,#8eacde,#6e82bc,#aac8e8,#729acc,#c8e4f3,#8eacde,#c8e4f3" />
	<groupColorInfo name="numbers" groupColor="#ff0000" groupOutlineColor="#dadada" nodeColorSequence="#ffacac,#ff8484,#ffc0c0,#ff9a9a,#ffd2d2" altNodeColorSequence="#ffacac,#ff8484,#ffc0c0,#ff9a9a,#ffd2d2" />
	<groupColorInfo name="accents" groupColor="#00c800" groupOutlineColor="#dadada" nodeColorSequence="#ffe600,#ffe66e" altNodeColorSequence="#ffe600,#ffe66e" />
	<groupColorInfo name="space" nodeColorSequence="#ebebeb" />
	<groupColorInfo name="paragraph" nodeColorSequence="#ebebeb" />
	<groupColorInfo name="paragraphSpace" nodeColorSequence="#ebebeb,#ebebeb" />
</colors>

=== willwade/DasherCoreRust/data/colors/color.rainbow.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE colors SYSTEM "color.dtd">
<colors name="Rainbow" parentName="Default" firstStartBoxColor="#ff9a9a" secondStartBoxColor="#ffd2d2" twoPushDynamicInactiveMarkerColor="#ffc888" twoPushDynamicOuterGuidesColor="#fff082">
	<groupColorInfo name="lowercase" nodeColorSequence="#ff7777,#f50000,#ff4545,#f98b00,#ff9c60,#ffc888,#ffe600,#fffa00,#fff082,#e6ffa0,#dfff00,#c8ff50,#00fa00,#00f714,#64ff78,#64ffc8,#00ffb9,#00ffc8,#00d7f0,#8cd7ff,#00cdff,#5a5aff,#0064f5,#8c8cff,#c35aff,#d76eff,#ff77d1,#d700fa,#fa00d1,#ff5ac0" altNodeColorSequence="#ff7777,#f50000,#ff4545,#f98b00,#ff9c60,#ffc888,#ffe600,#fffa00,#fff082,#e6ffa0,#dfff00,#c8ff50,#00fa00,#00f714,#64ff78,#64ffc8,#00ffb9,#00ffc8,#00d7f0,#8cd7ff,#00cdff,#5a5aff,#0064f5,#8c8cff,#c35aff,#d76eff,#ff77d1,#d700fa,#fa00d1,#ff5ac0" />
	<groupColorInfo name="lowercaseBackground" groupColor="#dcdcdc" groupOutlineColor="#dadada" nodeColorSequence="#ff7777,#f50000,#ff4545,#f98b00,#ff9c60,#ffc888,#ffe600,#fffa00,#fff082,#e6ffa0,#dfff00,#c8ff50,#00fa00,#00f714,#64ff78,#64ffc8,#00ffb9,#00ffc8,#00d7f0,#8cd7ff,#00cdff,#5a5aff,#0064f5,#8c8cff,#c35aff,#d76eff,#ff77d1,#d700fa,#fa00d1,#ff5ac0" altNodeColorSequence="#ff7777,#f50000,#ff4545,#f98b00,#ff9c60,#ffc888,#ffe600,#fffa00,#fff082,#e6ffa0,#dfff00,#c8ff50,#00fa00,#00f714,#64ff78,#64ffc8,#00ffb9,#00ffc8,#00d7f0,#8cd7ff,#00cdff,#5a5aff,#0064f5,#8c8cff,#c35aff,#d76eff,#ff77d1,#d700fa,#fa00d1,#ff5ac0" />
	<groupColorInfo name="uppercase" groupColor="#ffff00" groupOutlineColor="#dadada" nodeColorSequence="#ff7777,#f50000,#ff4545,#f98b00,#ff9c60,#ffc888,#ffe600,#fffa00,#fff082,#e6ffa0,#dfff00,#c8ff50,#00fa00,#00f714,#64ff78,#64ffc8,#00ffb9,#00ffc8,#00d7f0,#8cd7ff,#00cdff,#5a5aff,#0064f5,#8c8cff,#c35aff,#d76eff,#ff77d1,#d700fa,#fa00d1" altNodeColorSequence="#ff7777,#f50000,#ff4545,#f98b00,#ff9c60,#ffc888,#ffe600,#fffa00,#fff082,#e6ffa0,#dfff00,#c8ff50,#00fa00,#00f714,#64ff78,#64ffc8,#00ffb9,#00ffc8,#00d7f0,#8cd7ff,#00cdff,#5a5aff,#0064f5,#8c8cff,#c35aff,#d76eff,#ff77d1,#d700fa,#fa00d1" />
	<groupColorInfo name="punctuation" groupColor="#00c800" groupOutlineColor="#dadada" nodeColorSequence="#ff91ff,#729acc,#c8e4f3,#8eacde,#c8e4f3" altNodeColorSequence="#ff91ff,#729acc,#c8e4f3,#8eacde,#c8e4f3" />
	<groupColorInfo name="limitedPunctuation" groupColor="#00c800" groupOutlineColor="#dadada" nodeColorSequence="#dcdcdc,#ffb6ff,#ff91ff,#729acc,#c8e4f3,#8eacde,#c8e4f3" altNodeColorSequence="#dcdcdc,#ffb6ff,#ff91ff,#729acc,#c8e4f3,#8eacde,#c8e4f3" />
	<groupColorInfo name="punctuationLong" groupColor="#00c800" groupOutlineColor="#dadada" nodeColorSequence="#ffacac,#ff8484,#ffc0c0,#ff9a9a,#ffd2d2,#aaaaaa,#787878,#c3c3c3,#919191,#dcdcdc,#aaaaaa,#787878,#c3c3c3,#919191,#ff91ff,#ff52ff,#ffa2ff,#ff80ff,#ffb6ff,#ff91ff,#ff52ff,#ffa2ff,#ff80ff,#ffb6ff,#ff52ff,#ffa2ff,#ff80ff,#ffb6ff,#ff91ff,#ebebeb,#8eacde,#6e82bc,#aac8e8,#729acc,#c8e4f3,#8eacde,#c8e4f3" altNodeColorSequence="#ffacac,#ff8484,#ffc0c0,#ff9a9a,#ffd2d2,#aaaaaa,#787878,#c3c3c3,#919191,#dcdcdc,#aaaaaa,#787878,#c3c3c3,#919191,#ff91ff,#ff52ff,#ffa2ff,#ff80ff,#ffb6ff,#ff91ff,#ff52ff,#ffa2ff,#ff80ff,#ffb6ff,#ff52ff,#ffa2ff,#ff80ff,#ffb6ff,#ff91ff,#ffffff,#8eacde,#6e82bc,#aac8e8,#729acc,#c8e4f3,#8eacde,#c8e4f3" />
	<groupColorInfo name="numbers" groupColor="#ff0000" groupOutlineColor="#dadada" nodeColorSequence="#ffacac,#ff8484,#ffc0c0,#ff9a9a,#ffd2d2" altNodeColorSequence="#ffacac,#ff8484,#ffc0c0,#ff9a9a,#ffd2d2" />
	<groupColorInfo name="accents" groupColor="#00c800" groupOutlineColor="#dadada" nodeColorSequence="#ffe600,#ffe66e" altNodeColorSequence="#ffe600,#ffe66e" />
	<groupColorInfo name="space" nodeColorSequence="#ebebeb" />
	<groupColorInfo name="paragraph" nodeColorSequence="#ebebeb" />
	<groupColorInfo name="paragraphSpace" nodeColorSequence="#ebebeb,#ebebeb" />
</colors>

=== willwade/DasherCoreRust/data/colors/color.turbolut.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE colors SYSTEM "color.dtd">
<colors name="TurboLUT" parentName="Default" defaultOutlineColor="#323232" firstStartBoxColor="#ff9a9a" secondStartBoxColor="#ffd2d2" twoPushDynamicInactiveMarkerColor="#ffc888" twoPushDynamicOuterGuidesColor="#fff082" warningTextColor="#78787880">
	<groupColorInfo name="lowercase" nodeColorSequence="#bc96c6,#a7a3f7,#9aacff,#8eb5ff,#81beff,#71c9ff,#5bd5ff,#44e0ed,#30e9c7,#29eea5,#3ef17e,#62f157,#85ee36,#a1e824,#bde025,#d9d42f,#f1c738,#ffb93c,#ffa83c,#ff963b,#ff853c,#ff793e,#ff7142,#ff6f48,#ff7050,#ff755d,#ff77d1,#d700fa,#fa00d1,#ff5ac0" altNodeColorSequence="#caa4d4,#b5b1ff,#a8bbff,#9cc4ff,#90cdff,#81d8ff,#6de4ff,#59f0fd,#4af9d6,#45feb4,#53ff8c,#72ff65,#94fe46,#b0f936,#ccf036,#e8e43e,#ffd647,#ffc84a,#ffb749,#ffa548,#ff9348,#ff874a,#ff7f4e,#ff7d53,#ff7e5b,#ff8269,#ff77d1,#d700fa,#fa00d1,#ff5ac0" />
	<groupColorInfo name="lowercaseBackground" groupColor="#dcdcdc80" groupOutlineColor="#323232" nodeColorSequence="#bc96c6,#a7a3f7,#9aacff,#8eb5ff,#81beff,#71c9ff,#5bd5ff,#44e0ed,#30e9c7,#29eea5,#3ef17e,#62f157,#85ee36,#a1e824,#bde025,#d9d42f,#f1c738,#ffb93c,#ffa83c,#ff963b,#ff853c,#ff793e,#ff7142,#ff6f48,#ff7050,#ff755d,#ff77d1,#d700fa,#fa00d1,#ff5ac0" altNodeColorSequence="#caa4d4,#b5b1ff,#a8bbff,#9cc4ff,#90cdff,#81d8ff,#6de4ff,#59f0fd,#4af9d6,#45feb4,#53ff8c,#72ff65,#94fe46,#b0f936,#ccf036,#e8e43e,#ffd647,#ffc84a,#ffb749,#ffa548,#ff9348,#ff874a,#ff7f4e,#ff7d53,#ff7e5b,#ff8269,#ff77d1,#d700fa,#fa00d1,#ff5ac0" />
	<groupColorInfo name="uppercase" groupColor="#78787880" groupOutlineColor="#323232" nodeColorSequence="#bc96c6,#a7a3f7,#9aacff,#8eb5ff,#81beff,#71c9ff,#5bd5ff,#44e0ed,#30e9c7,#29eea5,#3ef17e,#62f157,#85ee36,#a1e824,#bde025,#d9d42f,#f1c738,#ffb93c,#ffa83c,#ff963b,#ff853c,#ff793e,#ff7142,#ff6f48,#ff7050,#ff755d,#ff77d1,#d700fa,#fa00d1" altNodeColorSequence="#caa4d4,#b5b1ff,#a8bbff,#9cc4ff,#90cdff,#81d8ff,#6de4ff,#59f0fd,#4af9d6,#45feb4,#53ff8c,#72ff65,#94fe46,#b0f936,#ccf036,#e8e43e,#ffd647,#ffc84a,#ffb749,#ffa548,#ff9348,#ff874a,#ff7f4e,#ff7d53,#ff7e5b,#ff8269,#ff77d1,#d700fa,#fa00d1" />
	<groupColorInfo name="punctuation" groupColor="#00c800" groupOutlineColor="#323232" nodeColorSequence="#ff91ff,#729acc,#c8e4f3,#8eacde,#c8e4f3" altNodeColorSequence="#ff91ff,#729acc,#c8e4f3,#8eacde,#c8e4f3" />
	<groupColorInfo name="limitedPunctuation" groupColor="#00c800" groupOutlineColor="#323232" nodeColorSequence="#dcdcdc80,#ffb6ff,#ff91ff,#729acc,#c8e4f3,#8eacde,#c8e4f3" altNodeColorSequence="#dcdcdc,#ffb6ff,#ff91ff,#729acc,#c8e4f3,#8eacde,#c8e4f3" />
	<groupColorInfo name="punctuationLong" groupColor="#00c800" groupOutlineColor="#323232" nodeColorSequence="#ffacac,#ff8484,#ffc0c0,#ff9a9a,#ffd2d2,#aaaaaa,#78787880,#c3c3c3,#919191,#dcdcdc80,#aaaaaa,#78787880,#c3c3c3,#919191,#ff91ff,#ff52ff,#ffa2ff,#ff80ff,#ffb6ff,#ff91ff,#ff52ff,#ffa2ff,#ff80ff,#ffb6ff,#ff52ff,#ffa2ff,#ff80ff,#ffb6ff,#ff91ff,#ebebeb,#8eacde,#6e82bc,#aac8e8,#729acc,#c8e4f3,#8eacde,#c8e4f3" altNodeColorSequence="#ffacac,#ff8484,#ffc0c0,#ff9a9a,#ffd2d2,#aaaaaa,#787878,#c3c3c3,#919191,#dcdcdc,#aaaaaa,#787878,#c3c3c3,#919191,#ff91ff,#ff52ff,#ffa2ff,#ff80ff,#ffb6ff,#ff91ff,#ff52ff,#ffa2ff,#ff80ff,#ffb6ff,#ff52ff,#ffa2ff,#ff80ff,#ffb6ff,#ff91ff,#ffffff,#8eacde,#6e82bc,#aac8e8,#729acc,#c8e4f3,#8eacde,#c8e4f3" />
	<groupColorInfo name="numbers" groupColor="#ff0000" groupOutlineColor="#323232" nodeColorSequence="#ffacac,#ff8484,#ffc0c0,#ff9a9a,#ffd2d2" altNodeColorSequence="#ffacac,#ff8484,#ffc0c0,#ff9a9a,#ffd2d2" />
	<groupColorInfo name="accents" groupColor="#00c800" groupOutlineColor="#323232" nodeColorSequence="#ffe600,#ffe66e" altNodeColorSequence="#ffe600,#ffe66e" />
	<groupColorInfo name="space" nodeColorSequence="#ebebeb" />
	<groupColorInfo name="paragraph" nodeColorSequence="#ebebeb" />
	<groupColorInfo name="paragraphSpace" nodeColorSequence="#ebebeb,#ebebeb" />
</colors>

=== willwade/DasherCoreRust/data/colors/color.yellow.on.blue.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE colors SYSTEM "color.dtd">
<colors name="Yellow on Blue" parentName="Default" backgroundColor="#000032" rootNodeColor="#088ab4" defaultOutlineColor="#afb9da" defaultLabelColor="#ffff37" firstStartBoxColor="#ff9a9a" secondStartBoxColor="#ffd2d2" twoPushDynamicInactiveMarkerColor="#ffc888" twoPushDynamicOuterGuidesColor="#fff082" infoTextColor="#000032" conversionNodeColor="#000023">
	<groupColorInfo name="lowercase" nodeColorSequence="#3226aa,#463796,#003764,#3226a0,#463296,#3226aa,#463796,#003764,#3226a0,#463296,#3226aa,#463796,#003764,#3226a0,#463296,#3226aa,#463796,#003764,#3226a0,#463296,#3226aa,#463796,#003764,#3226a0,#463296,#3226aa,#463796,#003764,#3226a0,#463296" altNodeColorSequence="#3c26b4,#5037a0,#08376c,#3c26aa,#5032a0,#3c26b4,#5037a0,#08376c,#3c26aa,#5032a0,#3c26b4,#5037a0,#08376c,#3c26aa,#5032a0,#3c26b4,#5037a0,#08376c,#3c26aa,#5032a0,#3c26b4,#5037a0,#08376c,#3c26aa,#5032a0,#3c26b4,#5037a0,#08376c,#3c26aa,#5032a0" />
	<groupColorInfo name="lowercaseBackground" groupColor="#dcdcdc" groupOutlineColor="#afb9da" nodeColorSequence="#3226aa,#463796,#003764,#3226a0,#463296,#3226aa,#463796,#003764,#3226a0,#463296,#3226aa,#463796,#003764,#3226a0,#463296,#3226aa,#463796,#003764,#3226a0,#463296,#3226aa,#463796,#003764,#3226a0,#463296,#3226aa,#463796,#003764,#3226a0,#463296" altNodeColorSequence="#3c26b4,#5037a0,#08376c,#3c26aa,#5032a0,#3c26b4,#5037a0,#08376c,#3c26aa,#5032a0,#3c26b4,#5037a0,#08376c,#3c26aa,#5032a0,#3c26b4,#5037a0,#08376c,#3c26aa,#5032a0,#3c26b4,#5037a0,#08376c,#3c26aa,#5032a0,#3c26b4,#5037a0,#08376c,#3c26aa,#5032a0" />
	<groupColorInfo name="uppercase" groupColor="#ffff00" groupOutlineColor="#afb9da" nodeColorSequence="#3226aa,#463796,#003764,#3226a0,#463296,#3226aa,#463796,#003764,#3226a0,#463296,#3226aa,#463796,#003764,#3226a0,#463296,#3226aa,#463796,#003764,#3226a0,#463296,#3226aa,#463796,#003764,#3226a0,#463296,#3226aa,#463796,#003764,#3226a0" altNodeColorSequence="#3c26b4,#5037a0,#08376c,#3c26aa,#5032a0,#3c26b4,#5037a0,#08376c,#3c26aa,#5032a0,#3c26b4,#5037a0,#08376c,#3c26aa,#5032a0,#3c26b4,#5037a0,#08376c,#3c26aa,#5032a0,#3c26b4,#5037a0,#08376c,#3c26aa,#5032a0,#3c26b4,#5037a0,#08376c,#3c26aa" />
	<groupColorInfo name="punctuation" groupColor="#00c800" groupOutlineColor="#afb9da" nodeColorSequence="#ff91ff,#729acc,#c8e4f3,#8eacde,#c8e4f3" altNodeColorSequence="#ff91ff,#729acc,#c8e4f3,#8eacde,#c8e4f3" />
	<groupColorInfo name="limitedPunctuation" groupColor="#00c800" groupOutlineColor="#afb9da" nodeColorSequence="#dcdcdc,#ffb6ff,#ff91ff,#729acc,#c8e4f3,#8eacde,#c8e4f3" altNodeColorSequence="#dcdcdc,#ffb6ff,#ff91ff,#729acc,#c8e4f3,#8eacde,#c8e4f3" />
	<groupColorInfo name="punctuationLong" groupColor="#00c800" groupOutlineColor="#afb9da" nodeColorSequence="#ffacac,#ff8484,#ffc0c0,#ff9a9a,#ffd2d2,#aaaaaa,#787878,#c3c3c3,#919191,#dcdcdc,#aaaaaa,#787878,#c3c3c3,#919191,#ff91ff,#ff52ff,#ffa2ff,#ff80ff,#ffb6ff,#ff91ff,#ff52ff,#ffa2ff,#ff80ff,#ffb6ff,#ff52ff,#ffa2ff,#ff80ff,#ffb6ff,#ff91ff,#000023,#8eacde,#6e82bc,#aac8e8,#729acc,#c8e4f3,#8eacde,#c8e4f3" altNodeColorSequence="#ffacac,#ff8484,#ffc0c0,#ff9a9a,#ffd2d2,#aaaaaa,#787878,#c3c3c3,#919191,#dcdcdc,#aaaaaa,#787878,#c3c3c3,#919191,#ff91ff,#ff52ff,#ffa2ff,#ff80ff,#ffb6ff,#ff91ff,#ff52ff,#ffa2ff,#ff80ff,#ffb6ff,#ff52ff,#ffa2ff,#ff80ff,#ffb6ff,#ff91ff,#000005,#8eacde,#6e82bc,#aac8e8,#729acc,#c8e4f3,#8eacde,#c8e4f3" />
	<groupColorInfo name="numbers" groupColor="#ff0000" groupOutlineColor="#afb9da" nodeColorSequence="#ffacac,#ff8484,#ffc0c0,#ff9a9a,#ffd2d2" altNodeColorSequence="#ffacac,#ff8484,#ffc0c0,#ff9a9a,#ffd2d2" />
	<groupColorInfo name="accents" groupColor="#00c800" groupOutlineColor="#afb9da" nodeColorSequence="#ffe600,#ffe66e" altNodeColorSequence="#ffe600,#ffe66e" />
	<groupColorInfo name="space" nodeColorSequence="#000023" />
	<groupColorInfo name="paragraph" nodeColorSequence="#000023" />
	<groupColorInfo name="paragraphSpace" nodeColorSequence="#000023,#000023" />
</colors>

=== willwade/DasherCoreRust/data/colors/color.default.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE colors SYSTEM "color.dtd">
<colors name="Default" backgroundColor="#ffffff" inputLineColor="#ff0000" inputPositionColor="#000000" crosshairColor="#000000" rootNodeColor="#b4eeb4" defaultOutlineColor="#dadada" defaultLabelColor="#000000" selectionHighlightColor="#ff0000" selectionInactiveColor="#000000" circleOutlineColor="#000000" circleStoppedColor="#ff0000" circleWaitingColor="#f0f000" circleStartedColor="#00ff00" firstStartBoxColor="#ff0000" secondStartBoxColor="#ffff00" twoPushDynamicActiveMarkerColor="#00ff00" twoPushDynamicInactiveMarkerColor="#00ffff" oneButtonDynamicOuterGuidesColor="#000000" twoPushDynamicOuterGuidesColor="#b4eeb4" infoTextColor="#ffffff" infoTextBackgroundColor="#000000" warningTextColor="#ffff00" warningTextBackgroundColor="#000000" gameGuideColor="#ff64cc" conversionNodeColor="#ebebeb">
	<groupColorInfo name="lowercase" nodeColorSequence="#00ffff,#b4eeb4,#9bcd9b,#00ffff,#b4eeb4,#9bcd9b,#00ffff,#b4eeb4,#9bcd9b,#00ffff,#b4eeb4,#9bcd9b,#00ffff,#b4eeb4,#9bcd9b,#00ffff,#b4eeb4,#9bcd9b,#00ffff,#b4eeb4,#9bcd9b,#00ffff,#b4eeb4,#9bcd9b,#00ffff,#b4eeb4,#9bcd9b,#00ffff,#b4eeb4,#9bcd9b" altNodeColorSequence="#87ceff,#ffaeb9,#ffbbff,#87ceff,#ffaeb9,#ffbbff,#87ceff,#ffaeb9,#ffbbff,#87ceff,#ffaeb9,#ffbbff,#87ceff,#ffaeb9,#ffbbff,#87ceff,#ffaeb9,#ffbbff,#87ceff,#ffaeb9,#ffbbff,#87ceff,#ffaeb9,#ffbbff,#87ceff,#ffaeb9,#ffbbff,#87ceff,#ffaeb9,#ffbbff" />
	<groupColorInfo name="lowercaseBackground" groupColor="#9bcd9b" groupOutlineColor="#dadada" nodeColorSequence="#00ffff,#b4eeb4,#9bcd9b,#00ffff,#b4eeb4,#9bcd9b,#00ffff,#b4eeb4,#9bcd9b,#00ffff,#b4eeb4,#9bcd9b,#00ffff,#b4eeb4,#9bcd9b,#00ffff,#b4eeb4,#9bcd9b,#00ffff,#b4eeb4,#9bcd9b,#00ffff,#b4eeb4,#9bcd9b,#00ffff,#b4eeb4,#9bcd9b,#00ffff,#b4eeb4,#9bcd9b" altNodeColorSequence="#87ceff,#ffaeb9,#ffbbff,#87ceff,#ffaeb9,#ffbbff,#87ceff,#ffaeb9,#ffbbff,#87ceff,#ffaeb9,#ffbbff,#87ceff,#ffaeb9,#ffbbff,#87ceff,#ffaeb9,#ffbbff,#87ceff,#ffaeb9,#ffbbff,#87ceff,#ffaeb9,#ffbbff,#87ceff,#ffaeb9,#ffbbff,#87ceff,#ffaeb9,#ffbbff" />
	<groupColorInfo name="uppercase" groupColor="#ffff00" groupOutlineColor="#dadada" nodeColorSequence="#00ffff,#b4eeb4,#9bcd9b,#00ffff,#b4eeb4,#9bcd9b,#00ffff,#b4eeb4,#9bcd9b,#00ffff,#b4eeb4,#9bcd9b,#00ffff,#b4eeb4,#9bcd9b,#00ffff,#b4eeb4,#9bcd9b,#00ffff,#b4eeb4,#9bcd9b,#00ffff,#b4eeb4,#9bcd9b,#00ffff,#b4eeb4,#9bcd9b,#00ffff,#b4eeb4" altNodeColorSequence="#87ceff,#ffaeb9,#ffbbff,#87ceff,#ffaeb9,#ffbbff,#87ceff,#ffaeb9,#ffbbff,#87ceff,#ffaeb9,#ffbbff,#87ceff,#ffaeb9,#ffbbff,#87ceff,#ffaeb9,#ffbbff,#87ceff,#ffaeb9,#ffbbff,#87ceff,#ffaeb9,#ffbbff,#87ceff,#ffaeb9,#ffbbff,#87ceff,#ffaeb9" />
	<groupColorInfo name="punctuation" groupColor="#00c800" groupOutlineColor="#dadada" nodeColorSequence="#9bcd9b,#00ffff,#b4eeb4,#00ffff,#b4eeb4" altNodeColorSequence="#ffbbff,#87ceff,#ffaeb9,#87ceff,#ffaeb9" />
	<groupColorInfo name="limitedPunctuation" groupColor="#00c800" groupOutlineColor="#dadada" nodeColorSequence="#9bcd9b,#00ffff,#9bcd9b,#00ffff,#b4eeb4,#00ffff,#b4eeb4" altNodeColorSequence="#ffbbff,#87ceff,#ffbbff,#87ceff,#ffaeb9,#87ceff,#ffaeb9" />
	<groupColorInfo name="punctuationLong" groupColor="#00c800" groupOutlineColor="#dadada" nodeColorSequence="#9bcd9b,#00ffff,#b4eeb4,#9bcd9b,#00ffff,#b4eeb4,#9bcd9b,#00ffff,#b4eeb4,#9bcd9b,#b4eeb4,#9bcd9b,#00ffff,#b4eeb4,#9bcd9b,#00ffff,#b4eeb4,#9bcd9b,#00ffff,#9bcd9b,#00ffff,#b4eeb4,#9bcd9b,#00ffff,#00ffff,#b4eeb4,#9bcd9b,#00ffff,#9bcd9b,#ebebeb,#00ffff,#b4eeb4,#9bcd9b,#00ffff,#b4eeb4,#00ffff,#b4eeb4" altNodeColorSequence="#ffbbff,#87ceff,#ffaeb9,#ffbbff,#87ceff,#ffaeb9,#ffbbff,#87ceff,#ffaeb9,#ffbbff,#ffaeb9,#ffbbff,#87ceff,#ffaeb9,#ffbbff,#87ceff,#ffaeb9,#ffbbff,#87ceff,#ffbbff,#87ceff,#ffaeb9,#ffbbff,#87ceff,#87ceff,#ffaeb9,#ffbbff,#87ceff,#ffbbff,#ffffff,#87ceff,#ffaeb9,#ffbbff,#87ceff,#ffaeb9,#87ceff,#ffaeb9" />
	<groupColorInfo name="numbers" groupColor="#ff0000" groupOutlineColor="#dadada" nodeColorSequence="#9bcd9b,#00ffff,#b4eeb4,#9bcd9b,#00ffff" altNodeColorSequence="#ffbbff,#87ceff,#ffaeb9,#ffbbff,#87ceff" />
	<groupColorInfo name="accents" groupColor="#00c800" groupOutlineColor="#dadada" nodeColorSequence="#9bcd9b,#00ffff" altNodeColorSequence="#ffbbff,#87ceff" />
	<groupColorInfo name="space" nodeColorSequence="#ebebeb" />
	<groupColorInfo name="paragraph" nodeColorSequence="#ebebeb" />
	<groupColorInfo name="paragraphSpace" nodeColorSequence="#ebebeb,#ebebeb" />
</colors>
