=== willwade/DasherCoreRust/data/colours/color.dtd
<!-- Color schemes contain defintions of colors to be used by Dasher -->
<!ELEMENT colors (groupColorInfo*)>
<!ATTLIST colors name CDATA #REQUIRED> <!-- Name of the ColorSchema -->
<!ATTLIST colors parentName CDATA "Default"> <!-- Parent ColorSchema from which missing data is inherited -->

<!-- Special Colors that are used in various places in Dasher Rendering -->
<!ATTLIST colors
    backgroundColor CDATA #IMPLIED
    crosshairColor CDATA #IMPLIED
    inputLineColor CDATA #IMPLIED
    inputPositionColor CDATA #IMPLIED
    rootNodeColor CDATA #IMPLIED
    defaultOutlineColor CDATA #IMPLIED
    defaultLabelColor CDATA #IMPLIED
    selectionHighlightColor CDATA #IMPLIED
    selectionInactiveColor CDATA #IMPLIED
    circleOutlineColor CDATA #IMPLIED
    circleStoppedColor CDATA #IMPLIED
    circleWaitingColor CDATA #IMPLIED
    circleStartedColor CDATA #IMPLIED
    firstStartBoxColor CDATA #IMPLIED
    secondStartBoxColor CDATA #IMPLIED
    twoPushDynamicActiveMarkerColor CDATA #IMPLIED
    twoPushDynamicInactiveMarkerColor CDATA #IMPLIED
    twoPushDynamicOuterGuidesColor CDATA #IMPLIED
    infoTextColor CDATA #IMPLIED
    infoTextBackgroundColor CDATA #IMPLIED
    warningTextColor CDATA #IMPLIED
    warningTextBackgroundColor CDATA #IMPLIED
    gameGuideColor CDATA #IMPLIED
    oneButtonDynamicOuterGuidesColor CDATA #IMPLIED
    conversionNodeColor CDATA #IMPLIED
>

<!-- Group Color Definition -->
<!ELEMENT groupColorInfo EMPTY>
<!ATTLIST groupColorInfo name CDATA #REQUIRED> <!-- Name of the Group that is referenced by the alphabet -->
<!ATTLIST groupColorInfo groupColor CDATA #IMPLIED> <!-- Color of the group itself -->
<!ATTLIST groupColorInfo altGroupColor CDATA #IMPLIED>
<!ATTLIST groupColorInfo groupOutlineColor CDATA #IMPLIED> <!-- OutlineColor of the group itself -->
<!ATTLIST groupColorInfo altGroupOutlineColor CDATA #IMPLIED>
<!ATTLIST groupColorInfo groupLabelColor CDATA #IMPLIED> <!-- LabelColor of the group itself -->
<!ATTLIST groupColorInfo altGroupLabelColor CDATA #IMPLIED>
 <!-- Sequence colors that are split and iterated in Dasher to cover the whole alphabet.
    A sequence is defined by a list of hex color values separated by commas.
    Example: nodeColorSequence="#B4DAA2FF,#BEEEBEFF" -->
<!ATTLIST groupColorInfo
    nodeColorSequence CDATA #IMPLIED
    altNodeColorSequence CDATA #IMPLIED
    nodeOutlineColorSequence CDATA #IMPLIED
    altNodeOutlineColorSequence CDATA #IMPLIED
    nodeLabelColorSequence CDATA #IMPLIED
    altNodeLabelColorSequence CDATA #IMPLIED
>

=== willwade/DasherCoreRust/data/colors/color.vowels.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE colors SYSTEM "color.dtd">
<colors name="Vowels" parentName="Default" firstStartBoxColor="#ff9a9a" secondStartBoxColor="#ffd2d2" twoPushDynamicInactiveMarkerColor="#ffc888" twoPushDynamicOuterGuidesColor="#fff082">
	<groupColorInfo name="lowercase" nodeColorSequence="#ffc888,#b4eeb4,#9bcd9b,#00ffff,#ffc888,#9bcd9b,#00ffff,#b4eeb4,#ffc888,#00ffff,#b4eeb4,#9bcd9b,#00ffff,#b4eeb4,#ffc888,#00ffff,#b4eeb4,#9bcd9b,#00ffff,#b4eeb4,#ffc888,#00ffff,#b4eeb4,#9bcd9b,#00ffff,#b4eeb4,#9bcd9b,#00ffff,#b4eeb4,#9bcd9b" altNodeColorSequence="#ff9c60,#ffaeb9,#ffbbff,#87ceff,#ff9c60,#ffbbff,#87ceff,#ffaeb9,#ff9c60,#87ceff,#ffaeb9,#ffbbff,#87ceff,#ffaeb9,#ff9c60,#87ceff,#ffaeb9,#ffbbff,#87ceff,#ffaeb9,#ff9c60,#87ceff,#ffaeb9,#ffbbff,#87ceff,#ffaeb9,#ffbbff,#87ceff,#ffaeb9,#ffbbff" />
	<groupColorInfo name="lowercaseBackground" groupColor="#dcdcdc" groupOutlineColor="#dadada" nodeColorSequence="#ffc888,#b4eeb4,#9bcd9b,#00ffff,#ffc888,#9bcd9b,#00ffff,#b4eeb4,#ffc888,#00ffff,#b4eeb4,#9bcd9b,#00ffff,#b4eeb4,#ffc888,#00ffff,#b4eeb4,#9bcd9b,#00ffff,#b4eeb4,#ffc888,#00ffff,#b4eeb4,#9bcd9b,#00ffff,#b4eeb4,#9bcd9b,#00ffff,#b4eeb4,#9bcd9b" altNodeColorSequence="#ff9c60,#ffaeb9,#ffbbff,#87ceff,#ff9c60,#ffbbff,#87ceff,#ffaeb9,#ff9c60,#87ceff,#ffaeb9,#ffbbff,#87ceff,#ffaeb9,#ff9c60,#87ceff,#ffaeb9,#ffbbff,#87ceff,#ffaeb9,#ff9c60,#87ceff,#ffaeb9,#ffbbff,#87ceff,#ffaeb9,#ffbbff,#87ceff,#ffaeb9,#ffbbff" />
	<groupColorInfo name="uppercase" groupColor="#ffff00" groupOutlineColor="#dadada" nodeColorSequence="#ffc888,#b4eeb4,#9bcd9b,#00ffff,#ffc888,#9bcd9b,#00ffff,#b4eeb4,#ffc888,#00ffff,#b4eeb4,#9bcd9b,#00ffff,#b4eeb4,#ffc888,#00ffff,#b4eeb4,#9bcd9b,#00ffff,#b4eeb4,#ffc888,#00ffff,#b4eeb4,#9bcd9b,#00ffff,#b4eeb4,#9bcd9b,#00ffff,#b4eeb4" altNodeColorSequence="#ff9c60,#ffaeb9,#ffbbff,#87ceff,#ff9c60,#ffbbff,#87ceff,#ffaeb9,#ff9c60,#87ceff,#ffaeb9,#ffbbff,#87ceff,#ffaeb9,#ff9c60,#87ceff,#ffaeb9,#ffbbff,#87ceff,#ffaeb9,#ff9c60,#87ceff,#ffaeb9,#ffbbff,#87ceff,#ffaeb9,#ffbbff,#87ceff,#ffaeb9" />
	<groupColorInfo name="punctuation" groupColor="#00c800" groupOutlineColor="#dadada" nodeColorSequence="#ff91ff,#729acc,#c8e4f3,#8eacde,#c8e4f3" altNodeColorSequence="#ff91ff,#729acc,#c8e4f3,#8eacde,#c8e4f3" />
	<groupColorInfo name="limitedPunctuation" groupColor="#00c800" groupOutlineColor="#dadada" nodeColorSequence="#dcdcdc,#ffb6ff,#ff91ff,#729acc,#c8e4f3,#8eacde,#c8e4f3" altNodeColorSequence="#dcdcdc,#ffb6ff,#ff91ff,#729acc,#c8e4f3,#8eacde,#c8e4f3" />
	<groupColorInfo name="punctuationLong" groupColor="#00c800" groupOutlineColor="#dadada" nodeColorSequence="#ffacac,#ff8484,#ffc0c0,#ff9a9a,#ffd2d2,#aaaaaa,#787878,#c3c3c3,#919191,#dcdcdc,#aaaaaa,#787878,#c3c3c3,#919191,#ff91ff,#ff52ff,#ffa2ff,#ff80ff,#ffb6ff,#ff91ff,#ff52ff,#ffa2ff,#ff80ff,#ffb6ff,#ff52ff,#ffa2ff,#ff80ff,#ffb6ff,#ff91ff,#ebebeb,#8eacde,#6e82bc,#aac8e8,#729acc,#c8e4f3,#8eacde,#c8e4f3" altNodeColorSequence="#ffacac,#ff8484,#ffc0c0,#ff9a9a,#ffd2d2,#aaaaaa,#787878,#c3c3c3,#919191,#dcdcdc,#aaaaaa,#787878,#c3c3c3,#919191,#ff91ff,#ff52ff,#ffa2ff,#ff80ff,#ffb6ff,#ff91ff,#ff52ff,#ffa2ff,#ff80ff,#ffb6ff,#ff52ff,#ffa2ff,#ff80ff,#ffb6ff,#ff91ff,#ffffff,#8eacde,#6e82bc,#aac8e8,#729acc,#c8e4f3,#8eacde,#c8e4f3" />
	<groupColorInfo name="numbers" groupColor="#ff0000" groupOutlineColor="#dadada" nodeColorSequence="#ffacac,#ff8484,#ffc0c0,#ff9a9a,#ffd2d2" altNodeColorSequence="#ffacac,#ff8484,#ffc0c0,#ff9a9a,#ffd2d2" />
	<groupColorInfo name="accents" groupColor="#00c800" groupOutlineColor="#dadada" nodeColorSequence="#ffe600,#ffe66e" altNodeColorSequence="#ffe600,#ffe66e" />
	<groupColorInfo name="space" nodeColorSequence="#ebebeb" />
	<groupColorInfo name="paragraph" nodeColorSequence="#ebebeb" />
	<groupColorInfo name="paragraphSpace" nodeColorSequence="#ebebeb,#ebebeb" />
</colors>

=== willwade/DasherCoreRust/data/colors/color.yellow.on.black.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE colors SYSTEM "color.dtd">
<colors name="Yellow on Black" parentName="Default" backgroundColor="#181712" inputLineColor="#3f3d38" inputPositionColor="#ffffff" rootNodeColor="#181712" defaultOutlineColor="#636363" defaultLabelColor="#ffff00" selectionHighlightColor="#3f3d38" selectionInactiveColor="#ffffff" circleOutlineColor="#ffffff" circleStoppedColor="#181712" firstStartBoxColor="#181712" secondStartBoxColor="#181712" twoPushDynamicInactiveMarkerColor="#181712" oneButtonDynamicOuterGuidesColor="#ffffff" twoPushDynamicOuterGuidesColor="#181712" infoTextColor="#181712" warningTextColor="#181712" conversionNodeColor="#000000">
	<groupColorInfo name="lowercase" nodeColorSequence="#181712,#181712,#181712,#181712,#181712,#181712,#181712,#181712,#181712,#181712,#181712,#181712,#181712,#181712,#181712,#181712,#181712,#181712,#181712,#181712,#181712,#181712,#181712,#181712,#181712,#181712,#181712,#181712,#181712,#181712" altNodeColorSequence="#181712,#181712,#181712,#181712,#181712,#181712,#181712,#181712,#181712,#181712,#181712,#181712,#181712,#181712,#181712,#181712,#181712,#181712,#181712,#181712,#181712,#181712,#181712,#181712,#181712,#181712,#181712,#181712,#181712,#181712" />
	<groupColorInfo name="lowercaseBackground" groupColor="#181712" groupOutlineColor="#636363" nodeColorSequence="#181712,#181712,#181712,#181712,#181712,#181712,#181712,#181712,#181712,#181712,#181712,#181712,#181712,#181712,#181712,#181712,#181712,#181712,#181712,#181712,#181712,#181712,#181712,#181712,#181712,#181712,#181712,#181712,#181712,#181712" altNodeColorSequence="#181712,#181712,#181712,#181712,#181712,#181712,#181712,#181712,#181712,#181712,#181712,#181712,#181712,#181712,#181712,#181712,#181712,#181712,#181712,#181712,#181712,#181712,#181712,#181712,#181712,#181712,#181712,#181712,#181712,#181712" />
	<groupColorInfo name="uppercase" groupColor="#181712" groupOutlineColor="#636363" nodeColorSequence="#181712,#181712,#181712,#181712,#181712,#181712,#181712,#181712,#181712,#181712,#181712,#181712,#181712,#181712,#181712,#181712,#181712,#181712,#181712,#181712,#181712,#181712,#181712,#181712,#181712,#181712,#181712,#181712,#181712" altNodeColorSequence="#181712,#181712,#181712,#181712,#181712,#181712,#181712,#181712,#181712,#181712,#181712,#181712,#181712,#181712,#181712,#181712,#181712,#181712,#181712,#181712,#181712,#181712,#181712,#181712,#181712,#181712,#181712,#181712,#181712" />
	<groupColorInfo name="punctuation" groupColor="#181712" groupOutlineColor="#636363" nodeColorSequence="#181712,#181712,#181712,#181712,#181712" altNodeColorSequence="#181712,#181712,#181712,#181712,#181712" />
	<groupColorInfo name="limitedPunctuation" groupColor="#181712" groupOutlineColor="#636363" nodeColorSequence="#181712,#181712,#181712,#181712,#181712,#181712,#181712" altNodeColorSequence="#181712,#181712,#181712,#181712,#181712,#181712,#181712" />
	<groupColorInfo name="punctuationLong" groupColor="#181712" groupOutlineColor="#636363" nodeColorSequence="#181712,#181712,#181712,#181712,#181712,#181712,#181712,#181712,#181712,#181712,#181712,#181712,#181712,#181712,#181712,#181712,#181712,#181712,#181712,#181712,#181712,#181712,#181712,#181712,#181712,#181712,#181712,#181712,#181712,#000000,#181712,#181712,#181712,#181712,#181712,#181712,#181712" altNodeColorSequence="#181712,#181712,#181712,#181712,#181712,#181712,#181712,#181712,#181712,#181712,#181712,#181712,#181712,#181712,#181712,#181712,#181712,#181712,#181712,#181712,#181712,#181712,#181712,#181712,#181712,#181712,#181712,#181712,#181712,#000000,#181712,#181712,#181712,#181712,#181712,#181712,#181712" />
	<groupColorInfo name="numbers" groupColor="#181712" groupOutlineColor="#636363" nodeColorSequence="#181712,#181712,#181712,#181712,#181712" altNodeColorSequence="#181712,#181712,#181712,#181712,#181712" />
	<groupColorInfo name="accents" groupColor="#181712" groupOutlineColor="#636363" nodeColorSequence="#181712,#181712" altNodeColorSequence="#181712,#181712" />
	<groupColorInfo name="space" nodeColorSequence="#000000" />
	<groupColorInfo name="paragraph" nodeColorSequence="#000000" />
	<groupColorInfo name="paragraphSpace" nodeColorSequence="#000000,#000000" />
</colors>
