=== willwade/DasherCoreRust/data/alphabets/alphabet.dtd
<!-- alphabet defintion for Dasher -->

<!ELEMENT alphabet (group*)>
<!ATTLIST alphabet name CDATA #REQUIRED> <!-- unique name that can be referenced in Dasher to choose this alphabet -->
<!ATTLIST alphabet orientation (LR|RL|TB|BT) #REQUIRED> <!-- orientation in which this alphabet is typed. Example: LR=Left-to-Right -->
<!ATTLIST alphabet conversionMode (none|mandarin|routingContextInsensitive|routingContextSensitive) "none"> <!-- conversion mode that is used internally to spawn a decoder that can handle phonetic writing -->
<!ATTLIST alphabet trainingFilename CDATA #IMPLIED> <!-- filename that is referenced for training the language model -->
<!ATTLIST alphabet colorsName CDATA "Default"> <!-- unique name of the color schema that should be used by default -->

<!-- Logical groups of symbols, eg name="lowercase" -->
<!ELEMENT group (node*|group*)>
<!ATTLIST group colorInfoName CDATA #IMPLIED>
<!ATTLIST group name CDATA #IMPLIED>
<!ATTLIST group label CDATA #IMPLIED>

<!-- Single symbols -->
<!ELEMENT node (textCharAction*|deleteTextAction*|moveCursorAction*|fixedTTSAction*|contextTTSAction*|repeatTTSAction*|stopTTSAction*|pauseDasherAction*|atspiAction*|keyboardAction*)>
<!ATTLIST node label CDATA #REQUIRED>
<!ATTLIST node text CDATA #IMPLIED> <!-- represents the text that is output and also used for training, defaults to the same value as label -->
<!ATTLIST node fixedProbability CDATA #IMPLIED>
<!ATTLIST node speedFactor CDATA #IMPLIED>

<!-- Actions that can happen if the node is selected -->

<!-- Text output: -->
<!ELEMENT textCharAction EMPTY>
<!ATTLIST textCharAction unicode CDATA #IMPLIED> <!-- If the Unicode value is unspecified, the label will be used to determine it. If the label is empty or consists of more than one character, an error will be thrown. -->

<!ELEMENT deleteTextAction EMPTY>
<!ATTLIST deleteTextAction distance CDATA #REQUIRED> <!-- Can be "(last|next) (char|word|sentence|paragraph)", or "all" -->

<!ELEMENT moveCursorAction EMPTY>
<!ATTLIST moveCursorAction distance CDATA #REQUIRED> <!-- Can be "(last|next) (char|word|sentence|paragraph)" -->

<!-- Text-to-Speech: -->
<!ELEMENT fixedTTSAction EMPTY>
<!ATTLIST fixedTTSAction text CDATA #REQUIRED> <!-- speaks out the given text -->

<!ELEMENT contextTTSAction EMPTY>
<!ATTLIST contextTTSAction context (word|sentence|paragraph|all) #REQUIRED> <!-- Reads out the last word/sentence/paragraph/all -->

<!ELEMENT repeatTTSAction EMPTY> <!-- Repeats the last TTS output -->

<!ELEMENT stopTTSAction EMPTY> <!-- Stops any currently ongoing TTS -->

<!-- Dasher-internal: -->
<!ELEMENT pauseDasherAction EMPTY> <!-- Stops any currently ongoing TTS -->
<!ATTLIST pauseDasherAction time CDATA #IMPLIED> <!-- Pauses Dasher for the given time, or stops forever if time is unspecified -->

<!-- System/application control: -->

<!ELEMENT changeSettingAction EMPTY>
<!ATTLIST changeSettingAction settingsName CDATA #REQUIRED> <!-- Stringname of the Setting -->
<!ATTLIST changeSettingAction doValue CDATA #IMPLIED> <!-- New Value of the Setting in case of selection -->
<!ATTLIST changeSettingAction undoValue CDATA #IMPLIED> <!-- New Value of the Setting in case of deselection -->

<!-- These two actions enable triggering any action in an application that can be bound to a keyboard shortcut or is accessible
     via the Assistive Technology Service Provider Interface (AT-SPI). Anything else probably isn't technically feasible. -->
<!ELEMENT atspiAction EMPTY>
<!ATTLIST atspiAction action CDATA #REQUIRED> <!-- Sends the specified AT-SPI action to the currently focused application -->
<!ATTLIST atspiAction undoAction CDATA #REQUIRED> <!-- Sends the specified AT-SPI action to the currently focused application -->

<!ELEMENT keyboardAction EMPTY>
<!ATTLIST keyboardAction key CDATA #IMPLIED> <!-- Emulates a keyboard shortcut, possibly with several modifiers, given as keyboard scancodes divided by commas (e.g. "1d,38,e053" for Ctrl+Alt+Entf), performing a press and a release -->
<!ATTLIST keyboardAction press CDATA #IMPLIED> <!-- As above, but only performing the press -->
<!ATTLIST keyboardAction release CDATA #IMPLIED> <!-- As above, but only performing the release -->
<!ATTLIST keyboardAction undoKey CDATA #IMPLIED> <!-- Emulates a keyboard shortcut, possibly with several modifiers, given as keyboard scancodes divided by commas (e.g. "1d,38,e053" for Ctrl+Alt+Entf), performing a press and a release -->
<!ATTLIST keyboardAction undoPress CDATA #IMPLIED> <!-- As above, but only performing the press -->
<!ATTLIST keyboardAction undoRelease CDATA #IMPLIED> <!-- As above, but only performing the release -->

<!-- External actions: -->
<!-- Similar to the socket input option, this action enables connecting Dasher to other accessibility tools, sending messages that the other tool can process. -->
<!ELEMENT socketOutputAction EMPTY>
<!ATTLIST socketOutputAction socketName CDATA #IMPLIED>
<!ATTLIST socketOutputAction doString CDATA #IMPLIED>
<!ATTLIST socketOutputAction undoString CDATA #IMPLIED>
<!ATTLIST socketOutputAction suppressNewline CDATA #IMPLIED>

<!-- Especially for the last two, it probably makes sense to add a windowTitle attribute to nodes: -->
<!-- <node label="New Tab" windowTitle=".*(Firefox|Chrome|Edge).*" fixedProbability="0.02"> Only shows this node if the title of the currently focused window matches the given regex. -->
 <!--  <atspiAction action="NewTab"/> -->
<!-- </node> -->

=== willwade/DasherCoreRust/data/alphabets/autoConverted/alphabet.polski.polish.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE alphabet SYSTEM "../alphabet.dtd">
<alphabet name="Polski / Polish" orientation="LR" trainingFilename="training_polish_PL.txt" colorsName="Default">
	<!--Created by: Krzysiek grandysk@go2.pl-->
	<group name="Małe litery">
		<node label="a">
			<textCharAction />
		</node>
		<node label="ą">
			<textCharAction />
		</node>
		<node label="b">
			<textCharAction />
		</node>
		<node label="c">
			<textCharAction />
		</node>
		<node label="ć">
			<textCharAction />
		</node>
		<node label="d">
			<textCharAction />
		</node>
		<node label="e">
			<textCharAction />
		</node>
		<node label="ę">
			<textCharAction />
		</node>
		<node label="f">
			<textCharAction />
		</node>
		<node label="g">
			<textCharAction />
		</node>
		<node label="h">
			<textCharAction />
		</node>
		<node label="i">
			<textCharAction />
		</node>
		<node label="j">
			<textCharAction />
		</node>
		<node label="k">
			<textCharAction />
		</node>
		<node label="l">
			<textCharAction />
		</node>
		<node label="ł">
			<textCharAction />
		</node>
		<node label="m">
			<textCharAction />
		</node>
		<node label="n">
			<textCharAction />
		</node>
		<node label="ń">
			<textCharAction />
		</node>
		<node label="o">
			<textCharAction />
		</node>
		<node label="ó">
			<textCharAction />
		</node>
		<node label="p">
			<textCharAction />
		</node>
		<node label="q">
			<textCharAction />
		</node>
		<node label="r">
			<textCharAction />
		</node>
		<node label="s">
			<textCharAction />
		</node>
		<node label="ś">
			<textCharAction />
		</node>
		<node label="t">
			<textCharAction />
		</node>
		<node label="u">
			<textCharAction />
		</node>
		<node label="v">
			<textCharAction />
		</node>
		<node label="w">
			<textCharAction />
		</node>
		<node label="x">
			<textCharAction />
		</node>
		<node label="y">
			<textCharAction />
		</node>
		<node label="z">
			<textCharAction />
		</node>
		<node label="ź">
			<textCharAction />
		</node>
		<node label="ż">
			<textCharAction />
		</node>
	</group>
	<group name="Duże litery" colorInfoName="duże litery">
		<!--Old Group Color: 111-->
		<node label="A">
			<textCharAction />
		</node>
		<node label="Ą">
			<textCharAction />
		</node>
		<node label="B">
			<textCharAction />
		</node>
		<node label="C">
			<textCharAction />
		</node>
		<node label="Ć">
			<textCharAction />
		</node>
		<node label="D">
			<textCharAction />
		</node>
		<node label="E">
			<textCharAction />
		</node>
		<node label="Ę">
			<textCharAction />
		</node>
		<node label="F">
			<textCharAction />
		</node>
		<node label="G">
			<textCharAction />
		</node>
		<node label="H">
			<textCharAction />
		</node>
		<node label="I">
			<textCharAction />
		</node>
		<node label="J">
			<textCharAction />
		</node>
		<node label="K">
			<textCharAction />
		</node>
		<node label="L">
			<textCharAction />
		</node>
		<node label="Ł">
			<textCharAction />
		</node>
		<node label="M">
			<textCharAction />
		</node>
		<node label="N">
			<textCharAction />
		</node>
		<node label="Ń">
			<textCharAction />
		</node>
		<node label="O">
			<textCharAction />
		</node>
		<node label="Ó">
			<textCharAction />
		</node>
		<node label="P">
			<textCharAction />
		</node>
		<node label="Q">
			<textCharAction />
		</node>
		<node label="R">
			<textCharAction />
		</node>
		<node label="S">
			<textCharAction />
		</node>
		<node label="Ś">
			<textCharAction />
		</node>
		<node label="T">
			<textCharAction />
		</node>
		<node label="U">
			<textCharAction />
		</node>
		<node label="V">
			<textCharAction />
		</node>
		<node label="W">
			<textCharAction />
		</node>
		<node label="X">
			<textCharAction />
		</node>
		<node label="Y">
			<textCharAction />
		</node>
		<node label="Z">
			<textCharAction />
		</node>
		<node label="Ź">
			<textCharAction />
		</node>
		<node label="Ż">
			<textCharAction />
		</node>
	</group>
	<group name="Liczby" colorInfoName="liczby">
		<!--Old Group Color: 113-->
		<node label="0">
			<textCharAction />
		</node>
		<node label="1">
			<textCharAction />
		</node>
		<node label="2">
			<textCharAction />
		</node>
		<node label="3">
			<textCharAction />
		</node>
		<node label="4">
			<textCharAction />
		</node>
		<node label="5">
			<textCharAction />
		</node>
		<node label="6">
			<textCharAction />
		</node>
		<node label="7">
			<textCharAction />
		</node>
		<node label="8">
			<textCharAction />
		</node>
		<node label="9">
			<textCharAction />
		</node>
	</group>
	<group name="Interpunkcja" colorInfoName="interpunkcja">
		<!--Old Group Color: 112-->
		<node label="%">
			<textCharAction />
		</node>
		<node label="*">
			<textCharAction />
		</node>
		<node label="+">
			<textCharAction />
		</node>
		<node label="=">
			<textCharAction />
		</node>
		<node label="/">
			<textCharAction />
		</node>
		<node label="#">
			<textCharAction />
		</node>
		<node label="$">
			<textCharAction />
		</node>
		<node label="|">
			<textCharAction />
		</node>
		<node label="\">
			<textCharAction />
		</node>
		<node label="~">
			<textCharAction />
		</node>
		<node label="^">
			<textCharAction />
		</node>
		<node label="_">
			<textCharAction />
		</node>
		<node label="&amp;">
			<textCharAction />
		</node>
		<node label="@">
			<textCharAction />
		</node>
		<node label="[">
			<textCharAction />
		</node>
		<node label="]">
			<textCharAction />
		</node>
		<node label="{">
			<textCharAction />
		</node>
		<node label="}">
			<textCharAction />
		</node>
		<node label="&lt;">
			<textCharAction />
		</node>
		<node label="&gt;">
			<textCharAction />
		</node>
		<node label="(">
			<textCharAction />
		</node>
		<node label=")">
			<textCharAction />
		</node>
		<node label="‹">
			<!--Note: French left single quotation mark-->
			<textCharAction />
		</node>
		<node label="›">
			<!--Note: French right single quotation mark-->
			<textCharAction />
		</node>
		<node label="«">
			<!--Note: French left double quotation mark-->
			<textCharAction />
		</node>
		<node label="»">
			<!--Note: French right double quotation mark-->
			<textCharAction />
		</node>
		<node label="&quot;">
			<textCharAction />
		</node>
		<node label="`">
			<textCharAction />
		</node>
		<node label="'">
			<textCharAction />
		</node>
		<node label="-">
			<textCharAction />
		</node>
		<node label=":">
			<textCharAction />
		</node>
		<node label=";">
			<textCharAction />
		</node>
		<node label="?">
			<textCharAction />
		</node>
		<node label="!">
			<textCharAction />
		</node>
		<node label=",">
			<textCharAction />
		</node>
		<node label=".">
			<textCharAction />
		</node>
	</group>
	<group name="paragraphSpace" colorInfoName="paragraphSpace">
		<node label="¶">
			<!--Old Char Color: 9-->
			<textCharAction />
		</node>
		<node label="□">
			<!--Old Char Color: 9-->
			<!--Note: box-->
			<textCharAction unicode="32" />
		</node>
	</group>
</alphabet>

=== willwade/DasherCoreRust/data/alphabets/autoConverted/alphabet.cherokee.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE alphabet SYSTEM "../alphabet.dtd">
<alphabet name="Cherokee" orientation="LR" trainingFilename="training_cherokee_US.txt" colorsName="European/Asian">
	<group name="A">
		<node label="Ꭰ">
			<!--Note:  CHEROKEE LETTER A  -->
			<textCharAction />
		</node>
		<node label="Ꭱ">
			<!--Note:  CHEROKEE LETTER E  -->
			<textCharAction />
		</node>
		<node label="Ꭲ">
			<!--Note:  CHEROKEE LETTER I  -->
			<textCharAction />
		</node>
		<node label="Ꭳ">
			<!--Note:  CHEROKEE LETTER O  -->
			<textCharAction />
		</node>
		<node label="Ꭴ">
			<!--Note:  CHEROKEE LETTER U  -->
			<textCharAction />
		</node>
		<node label="Ꭵ">
			<!--Note:  CHEROKEE LETTER V  -->
			<textCharAction />
		</node>
	</group>
	<group name="GA" colorInfoName="ga">
		<!--Old Group Color: 191-->
		<node label="Ꭶ">
			<!--Note:  CHEROKEE LETTER GA  -->
			<textCharAction />
		</node>
		<node label="Ꭷ">
			<!--Note:  CHEROKEE LETTER KA  -->
			<textCharAction />
		</node>
		<node label="Ꭸ">
			<!--Note:  CHEROKEE LETTER GE  -->
			<textCharAction />
		</node>
		<node label="Ꭹ">
			<!--Note:  CHEROKEE LETTER GI  -->
			<textCharAction />
		</node>
		<node label="Ꭺ">
			<!--Note:  CHEROKEE LETTER GO  -->
			<textCharAction />
		</node>
		<node label="Ꭻ">
			<!--Note:  CHEROKEE LETTER GU  -->
			<textCharAction />
		</node>
		<node label="Ꭼ">
			<!--Note:  CHEROKEE LETTER GV  -->
			<textCharAction />
		</node>
	</group>
	<group name="HA" colorInfoName="ha">
		<!--Old Group Color: 192-->
		<node label="Ꭽ">
			<!--Note:  CHEROKEE LETTER HA  -->
			<textCharAction />
		</node>
		<node label="Ꭾ">
			<!--Note:  CHEROKEE LETTER HE  -->
			<textCharAction />
		</node>
		<node label="Ꭿ">
			<!--Note:  CHEROKEE LETTER HI  -->
			<textCharAction />
		</node>
		<node label="Ꮀ">
			<!--Note:  CHEROKEE LETTER HO  -->
			<textCharAction />
		</node>
		<node label="Ꮁ">
			<!--Note:  CHEROKEE LETTER HU  -->
			<textCharAction />
		</node>
		<node label="Ꮂ">
			<!--Note:  CHEROKEE LETTER HV  -->
			<textCharAction />
		</node>
	</group>
	<group name="LA" colorInfoName="la">
		<!--Old Group Color: 193-->
		<node label="Ꮃ">
			<!--Note:  CHEROKEE LETTER LA  -->
			<textCharAction />
		</node>
		<node label="Ꮄ">
			<!--Note:  CHEROKEE LETTER LE  -->
			<textCharAction />
		</node>
		<node label="Ꮅ">
			<!--Note:  CHEROKEE LETTER LI  -->
			<textCharAction />
		</node>
		<node label="Ꮆ">
			<!--Note:  CHEROKEE LETTER LO  -->
			<textCharAction />
		</node>
		<node label="Ꮇ">
			<!--Note:  CHEROKEE LETTER LU  -->
			<textCharAction />
		</node>
		<node label="Ꮈ">
			<!--Note:  CHEROKEE LETTER LV  -->
			<textCharAction />
		</node>
	</group>
	<group name="MA" colorInfoName="ma">
		<!--Old Group Color: 194-->
		<node label="Ꮉ">
			<!--Note:  CHEROKEE LETTER MA  -->
			<textCharAction />
		</node>
		<node label="Ꮊ">
			<!--Note:  CHEROKEE LETTER ME  -->
			<textCharAction />
		</node>
		<node label="Ꮋ">
			<!--Note:  CHEROKEE LETTER MI  -->
			<textCharAction />
		</node>
		<node label="Ꮌ">
			<!--Note:  CHEROKEE LETTER MO  -->
			<textCharAction />
		</node>
		<node label="Ꮍ">
			<!--Note:  CHEROKEE LETTER MU  -->
			<textCharAction />
		</node>
	</group>
	<group name="NA" colorInfoName="na">
		<!--Old Group Color: 195-->
		<node label="Ꮎ">
			<!--Note:  CHEROKEE LETTER NA  -->
			<textCharAction />
		</node>
		<node label="Ꮏ">
			<!--Note:  CHEROKEE LETTER HNA  -->
			<textCharAction />
		</node>
		<node label="Ꮐ">
			<!--Note:  CHEROKEE LETTER NAH  -->
			<textCharAction />
		</node>
		<node label="Ꮑ">
			<!--Note:  CHEROKEE LETTER NE  -->
			<textCharAction />
		</node>
		<node label="Ꮒ">
			<!--Note:  CHEROKEE LETTER NI  -->
			<textCharAction />
		</node>
		<node label="Ꮓ">
			<!--Note:  CHEROKEE LETTER NO  -->
			<textCharAction />
		</node>
		<node label="Ꮔ">
			<!--Note:  CHEROKEE LETTER NU  -->
			<textCharAction />
		</node>
		<node label="Ꮕ">
			<!--Note:  CHEROKEE LETTER NV  -->
			<textCharAction />
		</node>
	</group>
	<group name="QUA" colorInfoName="qua">
		<!--Old Group Color: 196-->
		<node label="Ꮖ">
			<!--Note:  CHEROKEE LETTER QUA  -->
			<textCharAction />
		</node>
		<node label="Ꮗ">
			<!--Note:  CHEROKEE LETTER QUE  -->
			<textCharAction />
		</node>
		<node label="Ꮘ">
			<!--Note:  CHEROKEE LETTER QUI  -->
			<textCharAction />
		</node>
		<node label="Ꮙ">
			<!--Note:  CHEROKEE LETTER QUO  -->
			<textCharAction />
		</node>
		<node label="Ꮚ">
			<!--Note:  CHEROKEE LETTER QUU  -->
			<textCharAction />
		</node>
		<node label="Ꮛ">
			<!--Note:  CHEROKEE LETTER QUV  -->
			<textCharAction />
		</node>
	</group>
	<group name="SA" colorInfoName="sa">
		<!--Old Group Color: 197-->
		<node label="Ꮜ">
			<!--Note:  CHEROKEE LETTER SA  -->
			<textCharAction />
		</node>
		<node label="Ꮝ">
			<!--Note:  CHEROKEE LETTER S  -->
			<textCharAction />
		</node>
		<node label="Ꮞ">
			<!--Note:  CHEROKEE LETTER SE  -->
			<textCharAction />
		</node>
		<node label="Ꮟ">
			<!--Note:  CHEROKEE LETTER SI  -->
			<textCharAction />
		</node>
		<node label="Ꮠ">
			<!--Note:  CHEROKEE LETTER SO  -->
			<textCharAction />
		</node>
		<node label="Ꮡ">
			<!--Note:  CHEROKEE LETTER SU  -->
			<textCharAction />
		</node>
		<node label="Ꮢ">
			<!--Note:  CHEROKEE LETTER SV  -->
			<textCharAction />
		</node>
	</group>
	<group name="DA" colorInfoName="da">
		<!--Old Group Color: 198-->
		<node label="Ꮣ">
			<!--Note:  CHEROKEE LETTER DA  -->
			<textCharAction />
		</node>
		<node label="Ꮤ">
			<!--Note:  CHEROKEE LETTER TA  -->
			<textCharAction />
		</node>
		<node label="Ꮥ">
			<!--Note:  CHEROKEE LETTER DE  -->
			<textCharAction />
		</node>
		<node label="Ꮦ">
			<!--Note:  CHEROKEE LETTER TE  -->
			<textCharAction />
		</node>
		<node label="Ꮧ">
			<!--Note:  CHEROKEE LETTER DI  -->
			<textCharAction />
		</node>
		<node label="Ꮨ">
			<!--Note:  CHEROKEE LETTER TI  -->
			<textCharAction />
		</node>
		<node label="Ꮩ">
			<!--Note:  CHEROKEE LETTER DO  -->
			<textCharAction />
		</node>
		<node label="Ꮪ">
			<!--Note:  CHEROKEE LETTER DU  -->
			<textCharAction />
		</node>
		<node label="Ꮫ">
			<!--Note:  CHEROKEE LETTER DV  -->
			<textCharAction />
		</node>
	</group>
	<group name="DL" colorInfoName="dl">
		<!--Old Group Color: 199-->
		<node label="Ꮬ">
			<!--Note:  CHEROKEE LETTER DLA  -->
			<textCharAction />
		</node>
		<node label="Ꮭ">
			<!--Note:  CHEROKEE LETTER TLA  -->
			<textCharAction />
		</node>
		<node label="Ꮮ">
			<!--Note:  CHEROKEE LETTER TLE  -->
			<textCharAction />
		</node>
		<node label="Ꮯ">
			<!--Note:  CHEROKEE LETTER TLI  -->
			<textCharAction />
		</node>
		<node label="Ꮰ">
			<!--Note:  CHEROKEE LETTER TLO  -->
			<textCharAction />
		</node>
		<node label="Ꮱ">
			<!--Note:  CHEROKEE LETTER TLU  -->
			<textCharAction />
		</node>
		<node label="Ꮲ">
			<!--Note:  CHEROKEE LETTER TLV  -->
			<textCharAction />
		</node>
	</group>
	<group name="TS" colorInfoName="ts">
		<!--Old Group Color: 190-->
		<node label="Ꮳ">
			<!--Note:  CHEROKEE LETTER TSA  -->
			<textCharAction />
		</node>
		<node label="Ꮴ">
			<!--Note:  CHEROKEE LETTER TSE  -->
			<textCharAction />
		</node>
		<node label="Ꮵ">
			<!--Note:  CHEROKEE LETTER TSI  -->
			<textCharAction />
		</node>
		<node label="Ꮶ">
			<!--Note:  CHEROKEE LETTER TSO  -->
			<textCharAction />
		</node>
		<node label="Ꮷ">
			<!--Note:  CHEROKEE LETTER TSU  -->
			<textCharAction />
		</node>
		<node label="Ꮸ">
			<!--Note:  CHEROKEE LETTER TSV  -->
			<textCharAction />
		</node>
	</group>
	<group name="WA" colorInfoName="wa">
		<!--Old Group Color: 191-->
		<node label="Ꮹ">
			<!--Note:  CHEROKEE LETTER WA  -->
			<textCharAction />
		</node>
		<node label="Ꮺ">
			<!--Note:  CHEROKEE LETTER WE  -->
			<textCharAction />
		</node>
		<node label="Ꮻ">
			<!--Note:  CHEROKEE LETTER WI  -->
			<textCharAction />
		</node>
		<node label="Ꮼ">
			<!--Note:  CHEROKEE LETTER WO  -->
			<textCharAction />
		</node>
		<node label="Ꮽ">
			<!--Note:  CHEROKEE LETTER WU  -->
			<textCharAction />
		</node>
		<node label="Ꮾ">
			<!--Note:  CHEROKEE LETTER WV  -->
			<textCharAction />
		</node>
	</group>
	<group name="YA" colorInfoName="ya">
		<!--Old Group Color: 192-->
		<node label="Ꮿ">
			<!--Note:  CHEROKEE LETTER YA  -->
			<textCharAction />
		</node>
		<node label="Ᏸ">
			<!--Note:  CHEROKEE LETTER YE  -->
			<textCharAction />
		</node>
		<node label="Ᏹ">
			<!--Note:  CHEROKEE LETTER YI  -->
			<textCharAction />
		</node>
		<node label="Ᏺ">
			<!--Note:  CHEROKEE LETTER YO  -->
			<textCharAction />
		</node>
		<node label="Ᏻ">
			<!--Note:  CHEROKEE LETTER YU  -->
			<textCharAction />
		</node>
		<node label="Ᏼ">
			<!--Note:  CHEROKEE LETTER YV -->
			<textCharAction />
		</node>
	</group>
	<group name="paragraphSpace" colorInfoName="paragraphSpace">
		<node label="¶">
			<!--Old Char Color: 9-->
			<textCharAction />
		</node>
		<node label="□">
			<!--Old Char Color: 9-->
			<textCharAction unicode="32" />
		</node>
	</group>
</alphabet>

=== willwade/DasherCoreRust/data/alphabets/autoConverted/alphabet.lao.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE alphabet SYSTEM "../alphabet.dtd">
<alphabet name="Lao" orientation="LR" trainingFilename="training_lao_LA.txt" colorsName="European/Asian">
	<group name="lao tones (combining)">
		<node label="◌ໆ">
			<!--Note:  LAO KO LA  -->
			<textCharAction unicode="3782" />
		</node>
		<node label="◌່">
			<!--Note:  LAO TONE MAI EK  -->
			<textCharAction unicode="3784" />
		</node>
		<node label="◌້">
			<!--Note:  LAO TONE MAI THO  -->
			<textCharAction unicode="3785" />
		</node>
		<node label="◌໊">
			<!--Note:  LAO TONE MAI TI  -->
			<textCharAction unicode="3786" />
		</node>
		<node label="◌໋">
			<!--Note:  LAO TONE MAI CATAWA  -->
			<textCharAction unicode="3787" />
		</node>
	</group>
	<group name="Lao letters" colorInfoName="lao letters">
		<!--Old Group Color: 0-->
		<node label="ກ">
			<!--Note:  LAO LETTER KO  -->
			<textCharAction />
		</node>
		<node label="ຂ">
			<!--Note:  LAO LETTER KHO SUNG  -->
			<textCharAction />
		</node>
		<node label="ຄ">
			<!--Note:  LAO LETTER KHO TAM  -->
			<textCharAction />
		</node>
		<node label="ງ">
			<!--Note:  LAO LETTER NGO  -->
			<textCharAction />
		</node>
		<node label="ຈ">
			<!--Note:  LAO LETTER CO  -->
			<textCharAction />
		</node>
		<node label="ຊ">
			<!--Note:  LAO LETTER SO TAM  -->
			<textCharAction />
		</node>
		<node label="ຍ">
			<!--Note:  LAO LETTER NYO  -->
			<textCharAction />
		</node>
		<node label="ດ">
			<!--Note:  LAO LETTER DO  -->
			<textCharAction />
		</node>
		<node label="ຕ">
			<!--Note:  LAO LETTER TO  -->
			<textCharAction />
		</node>
		<node label="ຖ">
			<!--Note:  LAO LETTER THO SUNG  -->
			<textCharAction />
		</node>
		<node label="ທ">
			<!--Note:  LAO LETTER THO TAM  -->
			<textCharAction />
		</node>
		<node label="ນ">
			<!--Note:  LAO LETTER NO  -->
			<textCharAction />
		</node>
		<node label="ບ">
			<!--Note:  LAO LETTER BO  -->
			<textCharAction />
		</node>
		<node label="ປ">
			<!--Note:  LAO LETTER PO  -->
			<textCharAction />
		</node>
		<node label="ຜ">
			<!--Note:  LAO LETTER PHO SUNG  -->
			<textCharAction />
		</node>
		<node label="ຝ">
			<!--Note:  LAO LETTER FO TAM  -->
			<textCharAction />
		</node>
		<node label="ພ">
			<!--Note:  LAO LETTER PHO TAM  -->
			<textCharAction />
		</node>
		<node label="ຟ">
			<!--Note:  LAO LETTER FO SUNG  -->
			<textCharAction />
		</node>
		<node label="ມ">
			<!--Note:  LAO LETTER MO  -->
			<textCharAction />
		</node>
		<node label="ຢ">
			<!--Note:  LAO LETTER YO  -->
			<textCharAction />
		</node>
		<node label="ຣ">
			<!--Note:  LAO LETTER LO LING  -->
			<textCharAction />
		</node>
		<node label="ລ">
			<!--Note:  LAO LETTER LO LOOT  -->
			<textCharAction />
		</node>
		<node label="ວ">
			<!--Note:  LAO LETTER WO  -->
			<textCharAction />
		</node>
		<node label="ສ">
			<!--Note:  LAO LETTER SO SUNG  -->
			<textCharAction />
		</node>
		<node label="ຫ">
			<!--Note:  LAO LETTER HO SUNG  -->
			<textCharAction />
		</node>
		<node label="ອ">
			<!--Note:  LAO LETTER O  -->
			<textCharAction />
		</node>
		<node label="ຮ">
			<!--Note:  LAO LETTER HO TAM  -->
			<textCharAction />
		</node>
	</group>
	<group name="lao vowels (combining)" colorInfoName="lao vowels (combining)">
		<!--Old Group Color: 111-->
		<node label="◌ະ">
			<!--Note:  LAO VOWEL SIGN A  -->
			<textCharAction unicode="3760" />
		</node>
		<node label="◌ັ">
			<!--Note:  LAO VOWEL SIGN MAI KAN  -->
			<textCharAction unicode="3761" />
		</node>
		<node label="◌າ">
			<!--Note:  LAO VOWEL SIGN AA  -->
			<textCharAction unicode="3762" />
		</node>
		<node label="◌ຳ">
			<!--Note:  LAO VOWEL SIGN AM  -->
			<textCharAction unicode="3763" />
		</node>
		<node label="◌ິ">
			<!--Note:  LAO VOWEL SIGN I  -->
			<textCharAction unicode="3764" />
		</node>
		<node label="◌ີ">
			<!--Note:  LAO VOWEL SIGN II  -->
			<textCharAction unicode="3765" />
		</node>
		<node label="◌ຶ">
			<!--Note:  LAO VOWEL SIGN Y  -->
			<textCharAction unicode="3766" />
		</node>
		<node label="◌ື">
			<!--Note:  LAO VOWEL SIGN YY  -->
			<textCharAction unicode="3767" />
		</node>
		<node label="◌ຸ">
			<!--Note:  LAO VOWEL SIGN U  -->
			<textCharAction unicode="3768" />
		</node>
		<node label="◌ູ">
			<!--Note:  LAO VOWEL SIGN UU  -->
			<textCharAction unicode="3769" />
		</node>
		<node label="◌ົ">
			<!--Note:  LAO VOWEL SIGN MAI KON  -->
			<textCharAction unicode="3771" />
		</node>
		<node label="◌ຼ">
			<!--Note:  LAO SEMIVOWEL SIGN LO  -->
			<textCharAction unicode="3772" />
		</node>
		<node label="◌ຽ">
			<!--Note:  LAO SEMIVOWEL SIGN NYO  -->
			<textCharAction unicode="3773" />
		</node>
		<node label="◌ເ">
			<!--Note:  LAO VOWEL SIGN E  -->
			<textCharAction unicode="3776" />
		</node>
		<node label="◌ແ">
			<!--Note:  LAO VOWEL SIGN EI  -->
			<textCharAction unicode="3777" />
		</node>
		<node label="◌ໂ">
			<!--Note:  LAO VOWEL SIGN O  -->
			<textCharAction unicode="3778" />
		</node>
		<node label="◌ໃ">
			<!--Note:  LAO VOWEL SIGN AY  -->
			<textCharAction unicode="3779" />
		</node>
		<node label="◌ໄ">
			<!--Note:  LAO VOWEL SIGN AI  -->
			<textCharAction unicode="3780" />
		</node>
	</group>
	<group name="Punctuation?" colorInfoName="punctuation?">
		<!--Old Group Color: 112-->
		<node label="ຯ">
			<!--Note:  LAO ELLIPSIS  -->
			<textCharAction />
		</node>
		<node label="◌໌">
			<!--Note:  LAO CANCELLATION MARK  -->
			<textCharAction unicode="3788" />
		</node>
		<node label="◌ໍ">
			<!--Note:  LAO NIGGAHITA  -->
			<textCharAction unicode="3789" />
		</node>
		<node label="ໜ">
			<!--Note:  LAO HO NO  -->
			<textCharAction />
		</node>
		<node label="ໝ">
			<!--Note:  LAO HO MO -->
			<textCharAction />
		</node>
	</group>
	<group name="Numbers" colorInfoName="numbers">
		<!--Old Group Color: 113-->
		<node label="໐">
			<!--Note:  LAO DIGIT ZERO  -->
			<textCharAction />
		</node>
		<node label="໑">
			<!--Note:  LAO DIGIT ONE  -->
			<textCharAction />
		</node>
		<node label="໒">
			<!--Note:  LAO DIGIT TWO  -->
			<textCharAction />
		</node>
		<node label="໓">
			<!--Note:  LAO DIGIT THREE  -->
			<textCharAction />
		</node>
		<node label="໔">
			<!--Note:  LAO DIGIT FOUR  -->
			<textCharAction />
		</node>
		<node label="໕">
			<!--Note:  LAO DIGIT FIVE  -->
			<textCharAction />
		</node>
		<node label="໖">
			<!--Note:  LAO DIGIT SIX  -->
			<textCharAction />
		</node>
		<node label="໗">
			<!--Note:  LAO DIGIT SEVEN  -->
			<textCharAction />
		</node>
		<node label="໘">
			<!--Note:  LAO DIGIT EIGHT  -->
			<textCharAction />
		</node>
		<node label="໙">
			<!--Note:  LAO DIGIT NINE  -->
			<textCharAction />
		</node>
	</group>
	<group name="paragraphSpace" colorInfoName="paragraphSpace">
		<node label="¶">
			<!--Old Char Color: 9-->
			<textCharAction />
		</node>
		<node label="□">
			<!--Old Char Color: 9-->
			<textCharAction unicode="32" />
		</node>
	</group>
</alphabet>
