=== willwade/DasherCoreRust/data/alphabets/alphabet.dtd
<!-- alphabet defintion for Dasher -->

<!ELEMENT alphabet (group*)>
<!ATTLIST alphabet name CDATA #REQUIRED> <!-- unique name that can be referenced in Dasher to choose this alphabet -->
<!ATTLIST alphabet orientation (LR|RL|TB|BT) #REQUIRED> <!-- orientation in which this alphabet is typed. Example: LR=Left-to-Right -->
<!ATTLIST alphabet conversionMode (none|mandarin|routingContextInsensitive|routingContextSensitive) "none"> <!-- conversion mode that is used internally to spawn a decoder that can handle phonetic writing -->
<!ATTLIST alphabet trainingFilename CDATA #IMPLIED> <!-- filename that is referenced for training the language model -->
<!ATTLIST alphabet colorsName CDATA "Default"> <!-- unique name of the color schema that should be used by default -->

<!-- Logical groups of symbols, eg name="lowercase" -->
<!ELEMENT group (node*|group*)>
<!ATTLIST group colorInfoName CDATA #IMPLIED>
<!ATTLIST group name CDATA #IMPLIED>
<!ATTLIST group label CDATA #IMPLIED>

<!-- Single symbols -->
<!ELEMENT node (textCharAction*|deleteTextAction*|moveCursorAction*|fixedTTSAction*|contextTTSAction*|repeatTTSAction*|stopTTSAction*|pauseDasherAction*|atspiAction*|keyboardAction*)>
<!ATTLIST node label CDATA #REQUIRED>
<!ATTLIST node text CDATA #IMPLIED> <!-- represents the text that is output and also used for training, defaults to the same value as label -->
<!ATTLIST node fixedProbability CDATA #IMPLIED>
<!ATTLIST node speedFactor CDATA #IMPLIED>

<!-- Actions that can happen if the node is selected -->

<!-- Text output: -->
<!ELEMENT textCharAction EMPTY>
<!ATTLIST textCharAction unicode CDATA #IMPLIED> <!-- If the Unicode value is unspecified, the label will be used to determine it. If the label is empty or consists of more than one character, an error will be thrown. -->

<!ELEMENT deleteTextAction EMPTY>
<!ATTLIST deleteTextAction distance CDATA #REQUIRED> <!-- Can be "(last|next) (char|word|sentence|paragraph)", or "all" -->

<!ELEMENT moveCursorAction EMPTY>
<!ATTLIST moveCursorAction distance CDATA #REQUIRED> <!-- Can be "(last|next) (char|word|sentence|paragraph)" -->

<!-- Text-to-Speech: -->
<!ELEMENT fixedTTSAction EMPTY>
<!ATTLIST fixedTTSAction text CDATA #REQUIRED> <!-- speaks out the given text -->

<!ELEMENT contextTTSAction EMPTY>
<!ATTLIST contextTTSAction context (word|sentence|paragraph|all) #REQUIRED> <!-- Reads out the last word/sentence/paragraph/all -->

<!ELEMENT repeatTTSAction EMPTY> <!-- Repeats the last TTS output -->

<!ELEMENT stopTTSAction EMPTY> <!-- Stops any currently ongoing TTS -->

<!-- Dasher-internal: -->
<!ELEMENT pauseDasherAction EMPTY> <!-- Stops any currently ongoing TTS -->
<!ATTLIST pauseDasherAction time CDATA #IMPLIED> <!-- Pauses Dasher for the given time, or stops forever if time is unspecified -->

<!-- System/application control: -->

<!ELEMENT changeSettingAction EMPTY>
<!ATTLIST changeSettingAction settingsName CDATA #REQUIRED> <!-- Stringname of the Setting -->
<!ATTLIST changeSettingAction doValue CDATA #IMPLIED> <!-- New Value of the Setting in case of selection -->
<!ATTLIST changeSettingAction undoValue CDATA #IMPLIED> <!-- New Value of the Setting in case of deselection -->

<!-- These two actions enable triggering any action in an application that can be bound to a keyboard shortcut or is accessible
     via the Assistive Technology Service Provider Interface (AT-SPI). Anything else probably isn't technically feasible. -->
<!ELEMENT atspiAction EMPTY>
<!ATTLIST atspiAction action CDATA #REQUIRED> <!-- Sends the specified AT-SPI action to the currently focused application -->
<!ATTLIST atspiAction undoAction CDATA #REQUIRED> <!-- Sends the specified AT-SPI action to the currently focused application -->

<!ELEMENT keyboardAction EMPTY>
<!ATTLIST keyboardAction key CDATA #IMPLIED> <!-- Emulates a keyboard shortcut, possibly with several modifiers, given as keyboard scancodes divided by commas (e.g. "1d,38,e053" for Ctrl+Alt+Entf), performing a press and a release -->
<!ATTLIST keyboardAction press CDATA #IMPLIED> <!-- As above, but only performing the press -->
<!ATTLIST keyboardAction release CDATA #IMPLIED> <!-- As above, but only performing the release -->
<!ATTLIST keyboardAction undoKey CDATA #IMPLIED> <!-- Emulates a keyboard shortcut, possibly with several modifiers, given as keyboard scancodes divided by commas (e.g. "1d,38,e053" for Ctrl+Alt+Entf), performing a press and a release -->
<!ATTLIST keyboardAction undoPress CDATA #IMPLIED> <!-- As above, but only performing the press -->
<!ATTLIST keyboardAction undoRelease CDATA #IMPLIED> <!-- As above, but only performing the release -->

<!-- External actions: -->
<!-- Similar to the socket input option, this action enables connecting Dasher to other accessibility tools, sending messages that the other tool can process. -->
<!ELEMENT socketOutputAction EMPTY>
<!ATTLIST socketOutputAction socketName CDATA #IMPLIED>
<!ATTLIST socketOutputAction doString CDATA #IMPLIED>
<!ATTLIST socketOutputAction undoString CDATA #IMPLIED>
<!ATTLIST socketOutputAction suppressNewline CDATA #IMPLIED>

<!-- Especially for the last two, it probably makes sense to add a windowTitle attribute to nodes: -->
<!-- <node label="New Tab" windowTitle=".*(Firefox|Chrome|Edge).*" fixedProbability="0.02"> Only shows this node if the title of the currently focused window matches the given regex. -->
 <!--  <atspiAction action="NewTab"/> -->
<!-- </node> -->

=== willwade/DasherCoreRust/data/alphabets/autoConverted/alphabet.russian..alphabet.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE alphabet SYSTEM "../alphabet.dtd">
<alphabet name="Russian (Русский) - Кириллица alphabet" orientation="LR" trainingFilename="training_russian_RU.txt" colorsName="Default">
	<group name="lower case cyrillic (Кириллица) letters">
		<node label="а">
			<textCharAction />
		</node>
		<node label="б">
			<textCharAction />
		</node>
		<node label="в">
			<textCharAction />
		</node>
		<node label="г">
			<textCharAction />
		</node>
		<node label="д">
			<textCharAction />
		</node>
		<node label="е">
			<textCharAction />
		</node>
		<!-- <s d="&#x0450;" t="&#x0450;" note="not found in training text" /> -->
		<node label="ё">
			<!--Note: e with two dots - should this be 0407?-->
			<textCharAction />
		</node>
		<node label="ж">
			<textCharAction />
		</node>
		<node label="з">
			<textCharAction />
		</node>
		<node label="и">
			<textCharAction />
		</node>
		<node label="й">
			<textCharAction />
		</node>
		<node label="к">
			<textCharAction />
		</node>
		<node label="л">
			<textCharAction />
		</node>
		<node label="м">
			<textCharAction />
		</node>
		<node label="н">
			<textCharAction />
		</node>
		<node label="о">
			<textCharAction />
		</node>
		<node label="п">
			<textCharAction />
		</node>
		<node label="р">
			<textCharAction />
		</node>
		<node label="с">
			<textCharAction />
		</node>
		<node label="т">
			<textCharAction />
		</node>
		<node label="у">
			<textCharAction />
		</node>
		<node label="ф">
			<textCharAction />
		</node>
		<node label="х">
			<textCharAction />
		</node>
		<node label="ц">
			<textCharAction />
		</node>
		<node label="ч">
			<textCharAction />
		</node>
		<node label="ш">
			<textCharAction />
		</node>
		<node label="щ">
			<textCharAction />
		</node>
		<node label="ъ">
			<textCharAction />
		</node>
		<node label="ы">
			<textCharAction />
		</node>
		<node label="ь">
			<textCharAction />
		</node>
		<node label="э">
			<textCharAction />
		</node>
		<node label="ю">
			<textCharAction />
		</node>
		<node label="я">
			<textCharAction />
		</node>
	</group>
	<group name="upper case cyrillic (Кириллица) letters" colorInfoName="upper case cyrillic (кириллица) letters">
		<!--Old Group Color: 111-->
		<node label="А">
			<textCharAction />
		</node>
		<node label="Б">
			<textCharAction />
		</node>
		<node label="В">
			<textCharAction />
		</node>
		<node label="Г">
			<textCharAction />
		</node>
		<node label="Д">
			<textCharAction />
		</node>
		<node label="Е">
			<textCharAction />
		</node>
		<!-- <s d="&#x0400;" t="&#x0400;" note="not found in training text"  /> -->
		<node label="Ё">
			<!--Note: E with two dots - should this be 0406? -->
			<textCharAction />
		</node>
		<node label="Ж">
			<textCharAction />
		</node>
		<node label="З">
			<textCharAction />
		</node>
		<node label="И">
			<textCharAction />
		</node>
		<node label="Й">
			<textCharAction />
		</node>
		<node label="К">
			<textCharAction />
		</node>
		<node label="Л">
			<textCharAction />
		</node>
		<node label="М">
			<textCharAction />
		</node>
		<node label="Н">
			<textCharAction />
		</node>
		<node label="О">
			<textCharAction />
		</node>
		<node label="П">
			<textCharAction />
		</node>
		<node label="Р">
			<textCharAction />
		</node>
		<node label="С">
			<textCharAction />
		</node>
		<node label="Т">
			<textCharAction />
		</node>
		<node label="У">
			<textCharAction />
		</node>
		<node label="Ф">
			<textCharAction />
		</node>
		<node label="Х">
			<textCharAction />
		</node>
		<node label="Ц">
			<textCharAction />
		</node>
		<node label="Ч">
			<textCharAction />
		</node>
		<node label="Ш">
			<textCharAction />
		</node>
		<node label="Щ">
			<textCharAction />
		</node>
		<node label="Ъ">
			<textCharAction />
		</node>
		<node label="Ы">
			<textCharAction />
		</node>
		<node label="Ь">
			<textCharAction />
		</node>
		<node label="Э">
			<textCharAction />
		</node>
		<node label="Ю">
			<textCharAction />
		</node>
		<node label="Я">
			<textCharAction />
		</node>
	</group>
	<group name="Numbers" colorInfoName="numbers">
		<!--Old Group Color: 113-->
		<node label="1">
			<textCharAction />
		</node>
		<node label="2">
			<textCharAction />
		</node>
		<node label="3">
			<textCharAction />
		</node>
		<node label="4">
			<textCharAction />
		</node>
		<node label="5">
			<textCharAction />
		</node>
		<node label="6">
			<textCharAction />
		</node>
		<node label="7">
			<textCharAction />
		</node>
		<node label="8">
			<textCharAction />
		</node>
		<node label="9">
			<textCharAction />
		</node>
		<node label="0">
			<textCharAction />
		</node>
	</group>
	<group name="Punctuation" colorInfoName="punctuation">
		<!--Old Group Color: 112-->
		<node label="%">
			<textCharAction />
		</node>
		<node label="*">
			<textCharAction />
		</node>
		<node label="+">
			<textCharAction />
		</node>
		<node label="=">
			<textCharAction />
		</node>
		<node label="/">
			<textCharAction />
		</node>
		<node label="#">
			<textCharAction />
		</node>
		<node label="$">
			<textCharAction />
		</node>
		<node label="|">
			<textCharAction />
		</node>
		<node label="\">
			<textCharAction />
		</node>
		<node label="~">
			<textCharAction />
		</node>
		<node label="^">
			<textCharAction />
		</node>
		<node label="_">
			<textCharAction />
		</node>
		<node label="&amp;">
			<textCharAction />
		</node>
		<node label="@">
			<textCharAction />
		</node>
		<node label="[">
			<textCharAction />
		</node>
		<node label="]">
			<textCharAction />
		</node>
		<node label="{">
			<textCharAction />
		</node>
		<node label="}">
			<textCharAction />
		</node>
		<node label="&lt;">
			<textCharAction />
		</node>
		<node label="&gt;">
			<textCharAction />
		</node>
		<node label="(">
			<textCharAction />
		</node>
		<node label=")">
			<textCharAction />
		</node>
		<node label="‹">
			<!--Note: French left single quotation mark-->
			<textCharAction />
		</node>
		<node label="›">
			<!--Note: French right single quotation mark-->
			<textCharAction />
		</node>
		<node label="«">
			<!--Note: French left double quotation mark-->
			<textCharAction />
		</node>
		<node label="»">
			<!--Note: French right double quotation mark-->
			<textCharAction />
		</node>
		<node label="&quot;">
			<textCharAction />
		</node>
		<node label="`">
			<textCharAction />
		</node>
		<node label="'">
			<textCharAction />
		</node>
		<node label="-">
			<textCharAction />
		</node>
		<node label=":">
			<textCharAction />
		</node>
		<node label=";">
			<textCharAction />
		</node>
		<node label="?">
			<textCharAction />
		</node>
		<node label="!">
			<textCharAction />
		</node>
		<node label=",">
			<textCharAction />
		</node>
		<node label=".">
			<textCharAction />
		</node>
	</group>
	<group name="paragraphSpace" colorInfoName="paragraphSpace">
		<node label="¶">
			<!--Old Char Color: 9-->
			<textCharAction />
		</node>
		<node label="□">
			<!--Old Char Color: 9-->
			<textCharAction unicode="32" />
		</node>
	</group>
</alphabet>

=== willwade/DasherCoreRust/data/alphabets/autoConverted/alphabet.jane.austen.english.lower.case.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE alphabet SYSTEM "../alphabet.dtd">
<alphabet name="Jane Austen English Lower Case" orientation="LR" trainingFilename="training_emmaLC_GB.txt" colorsName="Default">
	<group name="Lower case Latin letters">
		<node label="a">
			<textCharAction />
		</node>
		<node label="b">
			<textCharAction />
		</node>
		<node label="c">
			<textCharAction />
		</node>
		<node label="d">
			<textCharAction />
		</node>
		<node label="e">
			<textCharAction />
		</node>
		<node label="f">
			<textCharAction />
		</node>
		<node label="g">
			<textCharAction />
		</node>
		<node label="h">
			<textCharAction />
		</node>
		<node label="i">
			<textCharAction />
		</node>
		<node label="j">
			<textCharAction />
		</node>
		<node label="k">
			<textCharAction />
		</node>
		<node label="l">
			<textCharAction />
		</node>
		<node label="m">
			<textCharAction />
		</node>
		<node label="n">
			<textCharAction />
		</node>
		<node label="o">
			<textCharAction />
		</node>
		<node label="p">
			<textCharAction />
		</node>
		<node label="q">
			<textCharAction />
		</node>
		<node label="r">
			<textCharAction />
		</node>
		<node label="s">
			<textCharAction />
		</node>
		<node label="t">
			<textCharAction />
		</node>
		<node label="u">
			<textCharAction />
		</node>
		<node label="v">
			<textCharAction />
		</node>
		<node label="w">
			<textCharAction />
		</node>
		<node label="x">
			<textCharAction />
		</node>
		<node label="y">
			<textCharAction />
		</node>
		<node label="z">
			<textCharAction />
		</node>
	</group>
	<group name="Punctuation" colorInfoName="punctuation">
		<!--Old Group Color: 112-->
		<node label=".">
			<!--Old Char Color: 9-->
			<textCharAction />
		</node>
	</group>
	<group name="paragraphSpace" colorInfoName="paragraphSpace">
		<node label="¶">
			<!--Old Char Color: 9-->
			<textCharAction />
		</node>
		<node label="□">
			<!--Old Char Color: 9-->
			<!--Note: box-->
			<textCharAction unicode="32" />
		</node>
	</group>
</alphabet>

=== willwade/DasherCoreRust/data/alphabets/autoConverted/alphabet.kannada.with.punctuation.and.numerals.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE alphabet SYSTEM "../alphabet.dtd">
<alphabet name="Kannada with punctuation and numerals" orientation="LR" trainingFilename="training_Kannada_IN.txt" colorsName="Default">
	<group name="KANNADA  letters">
		<node label="ಅ">
			<!--Note: KANNADA LETTER A -->
			<textCharAction />
		</node>
		<node label="ಆ">
			<!--Note: KANNADA LETTER AA -->
			<textCharAction />
		</node>
		<node label="ಇ">
			<!--Note: KANNADA LETTER I -->
			<textCharAction />
		</node>
		<node label="ಈ">
			<!--Note: KANNADA LETTER II -->
			<textCharAction />
		</node>
		<node label="ಉ">
			<!--Note: KANNADA LETTER U -->
			<textCharAction />
		</node>
		<node label="ಊ">
			<!--Note: KANNADA LETTER UU -->
			<textCharAction />
		</node>
		<node label="ಋ">
			<!--Note: KANNADA LETTER VOCALIC R -->
			<textCharAction />
		</node>
		<node label="ೠ">
			<!--Note: KANNADA LETTER VOCALIC RR -->
			<textCharAction />
		</node>
		<node label="ಌ">
			<!--Note: KANNADA LETTER VOCALIC L -->
			<textCharAction />
		</node>
		<node label="ೡ">
			<!--Note: KANNADA LETTER VOCALIC LL -->
			<textCharAction />
		</node>
		<node label="ಎ">
			<!--Note: KANNADA LETTER E -->
			<textCharAction />
		</node>
		<node label="ಏ">
			<!--Note: KANNADA LETTER EE -->
			<textCharAction />
		</node>
		<node label="ಐ">
			<!--Note: KANNADA LETTER AI -->
			<textCharAction />
		</node>
		<node label="ಒ">
			<!--Note: KANNADA LETTER O -->
			<textCharAction />
		</node>
		<node label="ಓ">
			<!--Note: KANNADA LETTER OO -->
			<textCharAction />
		</node>
		<node label="ಔ">
			<!--Note: KANNADA LETTER AU -->
			<textCharAction />
		</node>
		<node label="ಕ">
			<!--Note: KANNADA LETTER KA -->
			<textCharAction />
		</node>
		<node label="ಖ">
			<!--Note: KANNADA LETTER KHA -->
			<textCharAction />
		</node>
		<node label="ಗ">
			<!--Note: KANNADA LETTER GA -->
			<textCharAction />
		</node>
		<node label="ಘ">
			<!--Note: KANNADA LETTER GHA -->
			<textCharAction />
		</node>
		<node label="ಙ">
			<!--Note: KANNADA LETTER NGA -->
			<textCharAction />
		</node>
		<node label="ಚ">
			<!--Note: KANNADA LETTER CA -->
			<textCharAction />
		</node>
		<node label="ಛ">
			<!--Note: KANNADA LETTER CHA -->
			<textCharAction />
		</node>
		<node label="ಜ">
			<!--Note: KANNADA LETTER JA -->
			<textCharAction />
		</node>
		<node label="ಝ">
			<!--Note: KANNADA LETTER JHA -->
			<textCharAction />
		</node>
		<node label="ಞ">
			<!--Note: KANNADA LETTER NYA -->
			<textCharAction />
		</node>
		<node label="ಟ">
			<!--Note: KANNADA LETTER TTA -->
			<textCharAction />
		</node>
		<node label="ಠ">
			<!--Note: KANNADA LETTER TTHA -->
			<textCharAction />
		</node>
		<node label="ಡ">
			<!--Note: KANNADA LETTER DDA -->
			<textCharAction />
		</node>
		<node label="ಢ">
			<!--Note: KANNADA LETTER DDHA -->
			<textCharAction />
		</node>
		<node label="ಣ">
			<!--Note: KANNADA LETTER NNA -->
			<textCharAction />
		</node>
		<node label="ತ">
			<!--Note: KANNADA LETTER TA -->
			<textCharAction />
		</node>
		<node label="ಥ">
			<!--Note: KANNADA LETTER THA -->
			<textCharAction />
		</node>
		<node label="ದ">
			<!--Note: KANNADA LETTER DA -->
			<textCharAction />
		</node>
		<node label="ಧ">
			<!--Note: KANNADA LETTER DHA -->
			<textCharAction />
		</node>
		<node label="ನ">
			<!--Note: KANNADA LETTER NA -->
			<textCharAction />
		</node>
		<node label="ಪ">
			<!--Note: KANNADA LETTER PA -->
			<textCharAction />
		</node>
		<node label="ಫ">
			<!--Note: KANNADA LETTER PHA -->
			<textCharAction />
		</node>
		<node label="ಬ">
			<!--Note: KANNADA LETTER BA -->
			<textCharAction />
		</node>
		<node label="ಭ">
			<!--Note: KANNADA LETTER BHA -->
			<textCharAction />
		</node>
		<node label="ಮ">
			<!--Note: KANNADA LETTER MA -->
			<textCharAction />
		</node>
		<node label="ಯ">
			<!--Note: KANNADA LETTER YA -->
			<textCharAction />
		</node>
		<node label="ರ">
			<!--Note: KANNADA LETTER RA -->
			<textCharAction />
		</node>
		<node label="ಱ">
			<!--Note: KANNADA LETTER RRA -->
			<textCharAction />
		</node>
		<node label="ಲ">
			<!--Note: KANNADA LETTER LA -->
			<textCharAction />
		</node>
		<node label="ವ">
			<!--Note: KANNADA LETTER VA -->
			<textCharAction />
		</node>
		<node label="ಶ">
			<!--Note: KANNADA LETTER SHA -->
			<textCharAction />
		</node>
		<node label="ಷ">
			<!--Note: KANNADA LETTER SSA -->
			<textCharAction />
		</node>
		<node label="ಸ">
			<!--Note: KANNADA LETTER SA -->
			<textCharAction />
		</node>
		<node label="ಹ">
			<!--Note: KANNADA LETTER HA -->
			<textCharAction />
		</node>
		<node label="ಽ">
			<!--Note: KANNADA SIGN AVAGRAHA -->
			<textCharAction />
		</node>
		<node label="ಳ">
			<!--Note: KANNADA LETTER LLA -->
			<textCharAction />
		</node>
		<node label="ೞ">
			<!--Note: KANNADA LETTER FA -->
			<textCharAction />
		</node>
	</group>
	<group name="Kannada vowel signs and other marks" colorInfoName="kannada vowel signs and other marks">
		<!--Old Group Color: 111-->
		<node label="◌ಾ">
			<!--Note: KANNADA VOWEL SIGN AA -->
			<textCharAction unicode="3262" />
		</node>
		<node label="◌ಿ">
			<!--Note: KANNADA VOWEL SIGN I -->
			<textCharAction unicode="3263" />
		</node>
		<node label="◌ೀ">
			<!--Note: KANNADA VOWEL SIGN II -->
			<textCharAction unicode="3264" />
		</node>
		<node label="◌ು">
			<!--Note: KANNADA VOWEL SIGN U -->
			<textCharAction unicode="3265" />
		</node>
		<node label="◌ೂ">
			<!--Note: KANNADA VOWEL SIGN UU -->
			<textCharAction unicode="3266" />
		</node>
		<node label="◌ೃ">
			<!--Note: KANNADA VOWEL SIGN VOCALIC R -->
			<textCharAction unicode="3267" />
		</node>
		<node label="◌ೄ">
			<!--Note: KANNADA VOWEL SIGN VOCALIC RR -->
			<textCharAction unicode="3268" />
		</node>
		<node label="◌ೆ">
			<!--Note: KANNADA VOWEL SIGN E -->
			<textCharAction unicode="3270" />
		</node>
		<node label="◌ೇ">
			<!--Note: KANNADA VOWEL SIGN EE -->
			<textCharAction unicode="3271" />
		</node>
		<node label="◌ೈ">
			<!--Note: KANNADA VOWEL SIGN AI -->
			<textCharAction unicode="3272" />
		</node>
		<node label="◌ೊ">
			<!--Note: KANNADA VOWEL SIGN O -->
			<textCharAction unicode="3274" />
		</node>
		<node label="◌ೋ">
			<!--Note: KANNADA VOWEL SIGN OO -->
			<textCharAction unicode="3275" />
		</node>
		<node label="◌ೌ">
			<!--Note: KANNADA VOWEL SIGN AU -->
			<textCharAction unicode="3276" />
		</node>
		<node label="◌್">
			<!--Note: KANNADA SIGN VIRAMA -->
			<textCharAction unicode="3277" />
		</node>
		<node label="◌ೕ">
			<!--Note: KANNADA LENGTH MARK -->
			<textCharAction unicode="3285" />
		</node>
		<node label="◌ೖ">
			<!--Note: KANNADA AI LENGTH MARK -->
			<textCharAction unicode="3286" />
		</node>
	</group>
	<group name="Numbers" colorInfoName="numbers">
		<!--Old Group Color: 113-->
		<node label="1">
			<textCharAction />
		</node>
		<node label="2">
			<textCharAction />
		</node>
		<node label="3">
			<textCharAction />
		</node>
		<node label="4">
			<textCharAction />
		</node>
		<node label="5">
			<textCharAction />
		</node>
		<node label="6">
			<textCharAction />
		</node>
		<node label="7">
			<textCharAction />
		</node>
		<node label="8">
			<textCharAction />
		</node>
		<node label="9">
			<textCharAction />
		</node>
		<node label="0">
			<textCharAction />
		</node>
	</group>
	<group name="Punctuation" colorInfoName="punctuation">
		<!--Old Group Color: 112-->
		<node label="%">
			<textCharAction />
		</node>
		<node label="*">
			<textCharAction />
		</node>
		<node label="+">
			<textCharAction />
		</node>
		<node label="=">
			<textCharAction />
		</node>
		<node label="/">
			<textCharAction />
		</node>
		<node label="#">
			<textCharAction />
		</node>
		<node label="$">
			<textCharAction />
		</node>
		<node label="|">
			<textCharAction />
		</node>
		<node label="\">
			<textCharAction />
		</node>
		<node label="~">
			<textCharAction />
		</node>
		<node label="^">
			<textCharAction />
		</node>
		<node label="_">
			<textCharAction />
		</node>
		<node label="&amp;">
			<textCharAction />
		</node>
		<node label="@">
			<textCharAction />
		</node>
		<node label="[">
			<textCharAction />
		</node>
		<node label="]">
			<textCharAction />
		</node>
		<node label="{">
			<textCharAction />
		</node>
		<node label="}">
			<textCharAction />
		</node>
		<node label="&lt;">
			<textCharAction />
		</node>
		<node label="&gt;">
			<textCharAction />
		</node>
		<node label="(">
			<textCharAction />
		</node>
		<node label=")">
			<textCharAction />
		</node>
		<node label="&quot;">
			<textCharAction />
		</node>
		<node label="`">
			<textCharAction />
		</node>
		<node label="'">
			<textCharAction />
		</node>
		<node label="-">
			<textCharAction />
		</node>
		<node label=":">
			<textCharAction />
		</node>
		<node label=";">
			<textCharAction />
		</node>
		<node label="?">
			<textCharAction />
		</node>
		<node label="!">
			<textCharAction />
		</node>
		<node label=",">
			<textCharAction />
		</node>
		<node label="·">
			<textCharAction unicode="46" />
		</node>
	</group>
	<group name="paragraphSpace" colorInfoName="paragraphSpace">
		<node label="¶">
			<!--Old Char Color: 9-->
			<textCharAction />
		</node>
		<node label="□">
			<!--Old Char Color: 9-->
			<!--Note: box-->
			<textCharAction unicode="32" />
		</node>
	</group>
</alphabet>
