=== willwade/DasherCoreRust/data/alphabets/alphabet.dtd
<!-- alphabet defintion for Dasher -->

<!ELEMENT alphabet (group*)>
<!ATTLIST alphabet name CDATA #REQUIRED> <!-- unique name that can be referenced in Dasher to choose this alphabet -->
<!ATTLIST alphabet orientation (LR|RL|TB|BT) #REQUIRED> <!-- orientation in which this alphabet is typed. Example: LR=Left-to-Right -->
<!ATTLIST alphabet conversionMode (none|mandarin|routingContextInsensitive|routingContextSensitive) "none"> <!-- conversion mode that is used internally to spawn a decoder that can handle phonetic writing -->
<!ATTLIST alphabet trainingFilename CDATA #IMPLIED> <!-- filename that is referenced for training the language model -->
<!ATTLIST alphabet colorsName CDATA "Default"> <!-- unique name of the color schema that should be used by default -->

<!-- Logical groups of symbols, eg name="lowercase" -->
<!ELEMENT group (node*|group*)>
<!ATTLIST group colorInfoName CDATA #IMPLIED>
<!ATTLIST group name CDATA #IMPLIED>
<!ATTLIST group label CDATA #IMPLIED>

<!-- Single symbols -->
<!ELEMENT node (textCharAction*|deleteTextAction*|moveCursorAction*|fixedTTSAction*|contextTTSAction*|repeatTTSAction*|stopTTSAction*|pauseDasherAction*|atspiAction*|keyboardAction*)>
<!ATTLIST node label CDATA #REQUIRED>
<!ATTLIST node text CDATA #IMPLIED> <!-- represents the text that is output and also used for training, defaults to the same value as label -->
<!ATTLIST node fixedProbability CDATA #IMPLIED>
<!ATTLIST node speedFactor CDATA #IMPLIED>

<!-- Actions that can happen if the node is selected -->

<!-- Text output: -->
<!ELEMENT textCharAction EMPTY>
<!ATTLIST textCharAction unicode CDATA #IMPLIED> <!-- If the Unicode value is unspecified, the label will be used to determine it. If the label is empty or consists of more than one character, an error will be thrown. -->

<!ELEMENT deleteTextAction EMPTY>
<!ATTLIST deleteTextAction distance CDATA #REQUIRED> <!-- Can be "(last|next) (char|word|sentence|paragraph)", or "all" -->

<!ELEMENT moveCursorAction EMPTY>
<!ATTLIST moveCursorAction distance CDATA #REQUIRED> <!-- Can be "(last|next) (char|word|sentence|paragraph)" -->

<!-- Text-to-Speech: -->
<!ELEMENT fixedTTSAction EMPTY>
<!ATTLIST fixedTTSAction text CDATA #REQUIRED> <!-- speaks out the given text -->

<!ELEMENT contextTTSAction EMPTY>
<!ATTLIST contextTTSAction context (word|sentence|paragraph|all) #REQUIRED> <!-- Reads out the last word/sentence/paragraph/all -->

<!ELEMENT repeatTTSAction EMPTY> <!-- Repeats the last TTS output -->

<!ELEMENT stopTTSAction EMPTY> <!-- Stops any currently ongoing TTS -->

<!-- Dasher-internal: -->
<!ELEMENT pauseDasherAction EMPTY> <!-- Stops any currently ongoing TTS -->
<!ATTLIST pauseDasherAction time CDATA #IMPLIED> <!-- Pauses Dasher for the given time, or stops forever if time is unspecified -->

<!-- System/application control: -->

<!ELEMENT changeSettingAction EMPTY>
<!ATTLIST changeSettingAction settingsName CDATA #REQUIRED> <!-- Stringname of the Setting -->
<!ATTLIST changeSettingAction doValue CDATA #IMPLIED> <!-- New Value of the Setting in case of selection -->
<!ATTLIST changeSettingAction undoValue CDATA #IMPLIED> <!-- New Value of the Setting in case of deselection -->

<!-- These two actions enable triggering any action in an application that can be bound to a keyboard shortcut or is accessible
     via the Assistive Technology Service Provider Interface (AT-SPI). Anything else probably isn't technically feasible. -->
<!ELEMENT atspiAction EMPTY>
<!ATTLIST atspiAction action CDATA #REQUIRED> <!-- Sends the specified AT-SPI action to the currently focused application -->
<!ATTLIST atspiAction undoAction CDATA #REQUIRED> <!-- Sends the specified AT-SPI action to the currently focused application -->

<!ELEMENT keyboardAction EMPTY>
<!ATTLIST keyboardAction key CDATA #IMPLIED> <!-- Emulates a keyboard shortcut, possibly with several modifiers, given as keyboard scancodes divided by commas (e.g. "1d,38,e053" for Ctrl+Alt+Entf), performing a press and a release -->
<!ATTLIST keyboardAction press CDATA #IMPLIED> <!-- As above, but only performing the press -->
<!ATTLIST keyboardAction release CDATA #IMPLIED> <!-- As above, but only performing the release -->
<!ATTLIST keyboardAction undoKey CDATA #IMPLIED> <!-- Emulates a keyboard shortcut, possibly with several modifiers, given as keyboard scancodes divided by commas (e.g. "1d,38,e053" for Ctrl+Alt+Entf), performing a press and a release -->
<!ATTLIST keyboardAction undoPress CDATA #IMPLIED> <!-- As above, but only performing the press -->
<!ATTLIST keyboardAction undoRelease CDATA #IMPLIED> <!-- As above, but only performing the release -->

<!-- External actions: -->
<!-- Similar to the socket input option, this action enables connecting Dasher to other accessibility tools, sending messages that the other tool can process. -->
<!ELEMENT socketOutputAction EMPTY>
<!ATTLIST socketOutputAction socketName CDATA #IMPLIED>
<!ATTLIST socketOutputAction doString CDATA #IMPLIED>
<!ATTLIST socketOutputAction undoString CDATA #IMPLIED>
<!ATTLIST socketOutputAction suppressNewline CDATA #IMPLIED>

<!-- Especially for the last two, it probably makes sense to add a windowTitle attribute to nodes: -->
<!-- <node label="New Tab" windowTitle=".*(Firefox|Chrome|Edge).*" fixedProbability="0.02"> Only shows this node if the title of the currently focused window matches the given regex. -->
 <!--  <atspiAction action="NewTab"/> -->
<!-- </node> -->

=== willwade/DasherCoreRust/data/alphabets/autoConverted/alphabet.oriya.with.punctuation.and.numerals.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE alphabet SYSTEM "../alphabet.dtd">
<alphabet name="Oriya with punctuation and numerals" orientation="LR" trainingFilename="training_Oriya_IN.txt" colorsName="Default">
	<group name="ORIYA letters">
		<node label="ଅ">
			<!--Note: ORIYA LETTER A -->
			<textCharAction />
		</node>
		<node label="ଆ">
			<!--Note: ORIYA LETTER AA -->
			<textCharAction />
		</node>
		<node label="ଇ">
			<!--Note: ORIYA LETTER I -->
			<textCharAction />
		</node>
		<node label="ଈ">
			<!--Note: ORIYA LETTER II -->
			<textCharAction />
		</node>
		<node label="ଉ">
			<!--Note: ORIYA LETTER U -->
			<textCharAction />
		</node>
		<node label="ଊ">
			<!--Note: ORIYA LETTER UU -->
			<textCharAction />
		</node>
		<node label="ଋ">
			<!--Note: ORIYA LETTER VOCALIC R -->
			<textCharAction />
		</node>
		<node label="ୠ">
			<!--Note: ORIYA LETTER VOCALIC RR -->
			<textCharAction />
		</node>
		<node label="ଌ">
			<!--Note: ORIYA LETTER VOCALIC L -->
			<textCharAction />
		</node>
		<node label="ୡ">
			<!--Note: ORIYA LETTER VOCALIC LL -->
			<textCharAction />
		</node>
		<node label="ଏ">
			<!--Note: ORIYA LETTER E -->
			<textCharAction />
		</node>
		<node label="ଐ">
			<!--Note: ORIYA LETTER AI -->
			<textCharAction />
		</node>
		<node label="ଓ">
			<!--Note: ORIYA LETTER O -->
			<textCharAction />
		</node>
		<node label="ଔ">
			<!--Note: ORIYA LETTER AU -->
			<textCharAction />
		</node>
		<node label="କ">
			<!--Note: ORIYA LETTER KA -->
			<textCharAction />
		</node>
		<node label="ଖ">
			<!--Note: ORIYA LETTER KHA -->
			<textCharAction />
		</node>
		<node label="ଗ">
			<!--Note: ORIYA LETTER GA -->
			<textCharAction />
		</node>
		<node label="ଘ">
			<!--Note: ORIYA LETTER GHA -->
			<textCharAction />
		</node>
		<node label="ଙ">
			<!--Note: ORIYA LETTER NGA -->
			<textCharAction />
		</node>
		<node label="ଚ">
			<!--Note: ORIYA LETTER CA -->
			<textCharAction />
		</node>
		<node label="ଛ">
			<!--Note: ORIYA LETTER CHA -->
			<textCharAction />
		</node>
		<node label="ଜ">
			<!--Note: ORIYA LETTER JA -->
			<textCharAction />
		</node>
		<node label="ଝ">
			<!--Note: ORIYA LETTER JHA -->
			<textCharAction />
		</node>
		<node label="ଞ">
			<!--Note: ORIYA LETTER NYA -->
			<textCharAction />
		</node>
		<node label="ଟ">
			<!--Note: ORIYA LETTER TTA -->
			<textCharAction />
		</node>
		<node label="ଠ">
			<!--Note: ORIYA LETTER TTHA -->
			<textCharAction />
		</node>
		<node label="ଡ">
			<!--Note: ORIYA LETTER DDA -->
			<textCharAction />
		</node>
		<node label="ଡ଼">
			<!--Note: ORIYA LETTER RRA class(s)-->
			<textCharAction />
		</node>
		<node label="ଢ">
			<!--Note: ORIYA LETTER DDHA -->
			<textCharAction />
		</node>
		<node label="ଢ଼">
			<!--Note: ORIYA LETTER RHA class(s)-->
			<textCharAction />
		</node>
		<node label="ଣ">
			<!--Note: ORIYA LETTER NNA -->
			<textCharAction />
		</node>
		<node label="ତ">
			<!--Note: ORIYA LETTER TA -->
			<textCharAction />
		</node>
		<node label="ଥ">
			<!--Note: ORIYA LETTER THA -->
			<textCharAction />
		</node>
		<node label="ଦ">
			<!--Note: ORIYA LETTER DA -->
			<textCharAction />
		</node>
		<node label="ଧ">
			<!--Note: ORIYA LETTER DHA -->
			<textCharAction />
		</node>
		<node label="ନ">
			<!--Note: ORIYA LETTER NA -->
			<textCharAction />
		</node>
		<node label="ପ">
			<!--Note: ORIYA LETTER PA -->
			<textCharAction />
		</node>
		<node label="ଫ">
			<!--Note: ORIYA LETTER PHA -->
			<textCharAction />
		</node>
		<node label="ବ">
			<!--Note: ORIYA LETTER BA -->
			<textCharAction />
		</node>
		<node label="ଭ">
			<!--Note: ORIYA LETTER BHA -->
			<textCharAction />
		</node>
		<node label="ମ">
			<!--Note: ORIYA LETTER MA -->
			<textCharAction />
		</node>
		<node label="ଯ">
			<!--Note: ORIYA LETTER YA -->
			<textCharAction />
		</node>
		<node label="ୟ">
			<!--Note: ORIYA LETTER YYA -->
			<textCharAction />
		</node>
		<node label="ର">
			<!--Note: ORIYA LETTER RA -->
			<textCharAction />
		</node>
		<node label="ଲ">
			<!--Note: ORIYA LETTER LA -->
			<textCharAction />
		</node>
		<node label="ଳ">
			<!--Note: ORIYA LETTER LLA -->
			<textCharAction />
		</node>
		<node label="ଵ">
			<!--Note: ORIYA LETTER VA -->
			<textCharAction />
		</node>
		<node label="ୱ">
			<!--Note: ORIYA LETTER WA -->
			<textCharAction />
		</node>
		<node label="ଶ">
			<!--Note: ORIYA LETTER SHA -->
			<textCharAction />
		</node>
		<node label="ଷ">
			<!--Note: ORIYA LETTER SSA -->
			<textCharAction />
		</node>
		<node label="ସ">
			<!--Note: ORIYA LETTER SA -->
			<textCharAction />
		</node>
		<node label="ହ">
			<!--Note: ORIYA LETTER HA -->
			<textCharAction />
		</node>
	</group>
	<group name="vowels, other signs and marks">
		<node label="ଽ">
			<!--Note: ORIYA SIGN AVAGRAHA -->
			<textCharAction />
		</node>
		<node label="ା">
			<!--Note: ORIYA ◌ VOWEL SIGN AA -->
			<textCharAction />
		</node>
		<node label="ି">
			<!--Note: ORIYA ◌ VOWEL SIGN I -->
			<textCharAction />
		</node>
		<node label="ୀ">
			<!--Note: ORIYA ◌ VOWEL SIGN II -->
			<textCharAction />
		</node>
		<node label="ୁ">
			<!--Note: ORIYA ◌ VOWEL SIGN U -->
			<textCharAction />
		</node>
		<node label="ୂ">
			<!--Note: ORIYA ◌ VOWEL SIGN UU -->
			<textCharAction />
		</node>
		<node label="ୃ">
			<!--Note: ORIYA ◌ VOWEL SIGN VOCALIC R -->
			<textCharAction />
		</node>
		<node label="େ">
			<!--Note: ORIYA ◌ VOWEL SIGN E -->
			<textCharAction />
		</node>
		<node label="ୈ">
			<!--Note: ORIYA ◌ VOWEL SIGN AI -->
			<textCharAction />
		</node>
		<node label="ୋ">
			<!--Note: ORIYA ◌ VOWEL SIGN O -->
			<textCharAction />
		</node>
		<node label="ୌ">
			<!--Note: ORIYA ◌ VOWEL SIGN AU -->
			<textCharAction />
		</node>
		<node label="୍">
			<!--Note: ORIYA ◌ SIGN VIRAMA -->
			<textCharAction />
		</node>
		<node label="ୖ">
			<!--Note: ORIYA ◌ AI LENGTH MARK -->
			<textCharAction />
		</node>
		<node label="ୗ">
			<!--Note: ORIYA ◌ AU LENGTH MARK -->
			<textCharAction />
		</node>
	</group>
	<group name="Numbers" colorInfoName="numbers">
		<!--Old Group Color: 113-->
		<node label="1">
			<textCharAction />
		</node>
		<node label="2">
			<textCharAction />
		</node>
		<node label="3">
			<textCharAction />
		</node>
		<node label="4">
			<textCharAction />
		</node>
		<node label="5">
			<textCharAction />
		</node>
		<node label="6">
			<textCharAction />
		</node>
		<node label="7">
			<textCharAction />
		</node>
		<node label="8">
			<textCharAction />
		</node>
		<node label="9">
			<textCharAction />
		</node>
		<node label="0">
			<textCharAction />
		</node>
	</group>
	<group name="Punctuation" colorInfoName="punctuation">
		<!--Old Group Color: 112-->
		<node label="%">
			<textCharAction />
		</node>
		<node label="*">
			<textCharAction />
		</node>
		<node label="+">
			<textCharAction />
		</node>
		<node label="=">
			<textCharAction />
		</node>
		<node label="/">
			<textCharAction />
		</node>
		<node label="#">
			<textCharAction />
		</node>
		<node label="$">
			<textCharAction />
		</node>
		<node label="|">
			<textCharAction />
		</node>
		<node label="\">
			<textCharAction />
		</node>
		<node label="~">
			<textCharAction />
		</node>
		<node label="^">
			<textCharAction />
		</node>
		<node label="_">
			<textCharAction />
		</node>
		<node label="&amp;">
			<textCharAction />
		</node>
		<node label="@">
			<textCharAction />
		</node>
		<node label="[">
			<textCharAction />
		</node>
		<node label="]">
			<textCharAction />
		</node>
		<node label="{">
			<textCharAction />
		</node>
		<node label="}">
			<textCharAction />
		</node>
		<node label="&lt;">
			<textCharAction />
		</node>
		<node label="&gt;">
			<textCharAction />
		</node>
		<node label="(">
			<textCharAction />
		</node>
		<node label=")">
			<textCharAction />
		</node>
		<node label="&quot;">
			<textCharAction />
		</node>
		<node label="`">
			<textCharAction />
		</node>
		<node label="'">
			<textCharAction />
		</node>
		<node label="-">
			<textCharAction />
		</node>
		<node label=":">
			<textCharAction />
		</node>
		<node label=";">
			<textCharAction />
		</node>
		<node label="?">
			<textCharAction />
		</node>
		<node label="!">
			<textCharAction />
		</node>
		<node label=",">
			<textCharAction />
		</node>
		<node label=".">
			<textCharAction />
		</node>
	</group>
	<group name="paragraphSpace" colorInfoName="paragraphSpace">
		<node label="¶">
			<!--Old Char Color: 9-->
			<textCharAction />
		</node>
		<node label="□">
			<!--Old Char Color: 9-->
			<!--Note: box-->
			<textCharAction unicode="32" />
		</node>
	</group>
</alphabet>

=== willwade/DasherCoreRust/data/alphabets/autoConverted/alphabet.abc.musical.language.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE alphabet SYSTEM "../alphabet.dtd">
<alphabet name="Abc (Musical language)" orientation="LR" trainingFilename="training_abc_XX.txt" colorsName="European/Asian">
	<!-- alphabet file created from english.xml by David MacKay using
 information from http://www.lesession.co.uk/abc/abc_notation.htm .
 Rather than making Abc-specific groups, with a new alphabetical
 order, I thought it might be more user-friendly to stick with the
 English order. The only changes here are notes.
  See also  http://staffweb.cms.gre.ac.uk/~c.walshaw/abc/
 -->
	<group name="Second octave notes" colorInfoName="second octave notes">
		<node label="a">
			<!--Old Char Color: 10-->
			<textCharAction />
		</node>
		<node label="b">
			<!--Old Char Color: 11-->
			<textCharAction />
		</node>
		<node label="c">
			<!--Old Char Color: 12-->
			<textCharAction />
		</node>
		<node label="d">
			<!--Old Char Color: 13-->
			<textCharAction />
		</node>
		<node label="e">
			<!--Old Char Color: 14-->
			<textCharAction />
		</node>
		<node label="f">
			<!--Old Char Color: 15-->
			<textCharAction />
		</node>
		<node label="g">
			<!--Old Char Color: 16-->
			<textCharAction />
		</node>
		<!-- end notes -->
		<node label="h">
			<!--Old Char Color: 17-->
			<textCharAction />
		</node>
		<node label="i">
			<!--Old Char Color: 18-->
			<textCharAction />
		</node>
		<node label="j">
			<!--Old Char Color: 19-->
			<textCharAction />
		</node>
		<node label="k">
			<!--Old Char Color: 20-->
			<textCharAction />
		</node>
		<node label="l">
			<!--Old Char Color: 21-->
			<textCharAction />
		</node>
		<node label="m">
			<!--Old Char Color: 22-->
			<textCharAction />
		</node>
		<node label="n">
			<!--Old Char Color: 23-->
			<textCharAction />
		</node>
		<node label="o">
			<!--Old Char Color: 24-->
			<textCharAction />
		</node>
		<node label="p">
			<!--Old Char Color: 25-->
			<textCharAction />
		</node>
		<node label="q">
			<!--Old Char Color: 26-->
			<textCharAction />
		</node>
		<node label="r">
			<!--Old Char Color: 27-->
			<textCharAction />
		</node>
		<node label="s">
			<!--Old Char Color: 28-->
			<textCharAction />
		</node>
		<node label="t">
			<!--Old Char Color: 29-->
			<textCharAction />
		</node>
		<node label="u">
			<!--Old Char Color: 30-->
			<textCharAction />
		</node>
		<node label="v">
			<!--Old Char Color: 31-->
			<textCharAction />
		</node>
		<node label="w">
			<!--Old Char Color: 32-->
			<textCharAction />
		</node>
		<node label="x">
			<!--Old Char Color: 33-->
			<textCharAction />
		</node>
		<node label="y">
			<!--Old Char Color: 34-->
			<textCharAction />
		</node>
		<!-- -->
		<node label="z">
			<!--Old Char Color: 35-->
			<!--Note: rest-->
			<textCharAction />
		</node>
	</group>
	<group name="First octave notes" colorInfoName="first octave notes">
		<!--Old Group Color: 111-->
		<node label="A">
			<!--Old Char Color: 10-->
			<textCharAction />
		</node>
		<node label="B">
			<!--Old Char Color: 11-->
			<textCharAction />
		</node>
		<node label="C">
			<!--Old Char Color: 12-->
			<!--Note: composer-->
			<textCharAction />
		</node>
		<node label="D">
			<!--Old Char Color: 13-->
			<textCharAction />
		</node>
		<node label="E">
			<!--Old Char Color: 14-->
			<textCharAction />
		</node>
		<node label="F">
			<!--Old Char Color: 15-->
			<textCharAction />
		</node>
		<node label="G">
			<!--Old Char Color: 16-->
			<textCharAction />
		</node>
		<node label="H">
			<!--Old Char Color: 17-->
			<textCharAction />
		</node>
		<node label="I">
			<!--Old Char Color: 18-->
			<textCharAction />
		</node>
		<node label="J">
			<!--Old Char Color: 19-->
			<textCharAction />
		</node>
		<node label="K">
			<!--Old Char Color: 20-->
			<!--Note: key signature-->
			<textCharAction />
		</node>
		<node label="L">
			<!--Old Char Color: 21-->
			<!--Note: default duration-->
			<textCharAction />
		</node>
		<node label="M">
			<!--Old Char Color: 22-->
			<!--Note: meter-->
			<textCharAction />
		</node>
		<node label="N">
			<!--Old Char Color: 23-->
			<!--Note: notes-->
			<textCharAction />
		</node>
		<node label="O">
			<!--Old Char Color: 24-->
			<!--Note: origin-->
			<textCharAction />
		</node>
		<node label="P">
			<!--Old Char Color: 25-->
			<textCharAction />
		</node>
		<node label="Q">
			<!--Old Char Color: 26-->
			<!--Note: tempo-->
			<textCharAction />
		</node>
		<node label="R">
			<!--Old Char Color: 27-->
			<textCharAction />
		</node>
		<node label="S">
			<!--Old Char Color: 28-->
			<!--Note: source-->
			<textCharAction />
		</node>
		<node label="T">
			<!--Old Char Color: 29-->
			<!--Note: title-->
			<textCharAction />
		</node>
		<node label="U">
			<!--Old Char Color: 30-->
			<textCharAction />
		</node>
		<node label="V">
			<!--Old Char Color: 31-->
			<textCharAction />
		</node>
		<node label="W">
			<!--Old Char Color: 32-->
			<textCharAction />
		</node>
		<node label="X">
			<!--Old Char Color: 33-->
			<!--Note: index-->
			<textCharAction />
		</node>
		<node label="Y">
			<!--Old Char Color: 34-->
			<textCharAction />
		</node>
		<node label="Z">
			<!--Old Char Color: 35-->
			<!--Note: transcriber-->
			<textCharAction />
		</node>
	</group>
	<group name="Numbers" colorInfoName="numbers">
		<!--Old Group Color: 113-->
		<node label="1">
			<!--Old Char Color: 90-->
			<textCharAction />
		</node>
		<node label="2">
			<!--Old Char Color: 105-->
			<textCharAction />
		</node>
		<node label="3">
			<!--Old Char Color: 91-->
			<textCharAction />
		</node>
		<node label="4">
			<!--Old Char Color: 106-->
			<textCharAction />
		</node>
		<node label="5">
			<!--Old Char Color: 92-->
			<textCharAction />
		</node>
		<node label="6">
			<!--Old Char Color: 107-->
			<textCharAction />
		</node>
		<node label="7">
			<!--Old Char Color: 93-->
			<textCharAction />
		</node>
		<node label="8">
			<!--Old Char Color: 108-->
			<textCharAction />
		</node>
		<node label="9">
			<!--Old Char Color: 94-->
			<textCharAction />
		</node>
		<node label="0">
			<!--Old Char Color: 109-->
			<textCharAction />
		</node>
	</group>
	<group name="Annotation" colorInfoName="annotation">
		<!--Old Group Color: 112-->
		<node label="%">
			<!--Old Char Color: 90-->
			<textCharAction />
		</node>
		<node label="*">
			<!--Old Char Color: 91-->
			<textCharAction />
		</node>
		<node label="+">
			<!--Old Char Color: 92-->
			<textCharAction />
		</node>
		<node label="=">
			<!--Old Char Color: 93-->
			<!--Note: natural-->
			<textCharAction />
		</node>
		<node label="/">
			<!--Old Char Color: 94-->
			<textCharAction />
		</node>
		<node label="#">
			<!--Old Char Color: 95-->
			<textCharAction />
		</node>
		<node label="$">
			<!--Old Char Color: 96-->
			<textCharAction />
		</node>
		<node label="|">
			<!--Old Char Color: 97-->
			<textCharAction />
		</node>
		<node label="\">
			<!--Old Char Color: 98-->
			<textCharAction />
		</node>
		<node label="~">
			<!--Old Char Color: 99-->
			<!--Note: grace note-->
			<textCharAction />
		</node>
		<node label="^">
			<!--Old Char Color: 95-->
			<!--Note: sharp-->
			<textCharAction />
		</node>
		<node label="_">
			<!--Old Char Color: 96-->
			<!--Note: flat-->
			<textCharAction />
		</node>
		<node label="&amp;">
			<!--Old Char Color: 97-->
			<textCharAction />
		</node>
		<node label="@">
			<!--Old Char Color: 98-->
			<textCharAction />
		</node>
		<node label="[">
			<!--Old Char Color: 105-->
			<textCharAction />
		</node>
		<node label="]">
			<!--Old Char Color: 106-->
			<textCharAction />
		</node>
		<node label="{">
			<!--Old Char Color: 107-->
			<textCharAction />
		</node>
		<node label="}">
			<!--Old Char Color: 108-->
			<textCharAction />
		</node>
		<node label="&lt;">
			<!--Old Char Color: 109-->
			<textCharAction />
		</node>
		<node label="&gt;">
			<!--Old Char Color: 105-->
			<textCharAction />
		</node>
		<node label="(">
			<!--Old Char Color: 106-->
			<textCharAction />
		</node>
		<node label=")">
			<!--Old Char Color: 107-->
			<textCharAction />
		</node>
		<node label="“">
			<!--Old Char Color: 108-->
			<!--Note: left double quotation mark-->
			<textCharAction />
		</node>
		<node label="&quot;">
			<!--Old Char Color: 109-->
			<!--Note: deprecated vertical double quotation mark-->
			<textCharAction />
		</node>
		<node label="”">
			<!--Old Char Color: 106-->
			<!--Note: right double quotation mark-->
			<textCharAction />
		</node>
		<node label="‘">
			<!--Old Char Color: 107-->
			<!--Note: left single quotation mark-->
			<textCharAction />
		</node>
		<node label="’">
			<!--Old Char Color: 108-->
			<!--Note: right single quotation mark and apostrophe-->
			<textCharAction />
		</node>
		<node label="`">
			<!--Old Char Color: 109-->
			<!--Note: left quote from keyboard-->
			<textCharAction />
		</node>
		<node label="'">
			<!--Old Char Color: 105-->
			<!--Note: up an octave-->
			<textCharAction />
		</node>
		<node label="-">
			<!--Old Char Color: 100-->
			<!--Note: tie notes of same pitch-->
			<textCharAction />
		</node>
		<node label=":">
			<!--Old Char Color: 101-->
			<!--Note: used in repeats and in header-->
			<textCharAction />
		</node>
		<node label=";">
			<!--Old Char Color: 102-->
			<textCharAction />
		</node>
		<node label="?">
			<!--Old Char Color: 103-->
			<textCharAction />
		</node>
		<node label="!">
			<!--Old Char Color: 104-->
			<textCharAction />
		</node>
		<node label=",">
			<!--Old Char Color: 100-->
			<!--Note: down an octave-->
			<textCharAction />
		</node>
		<node label=".">
			<!--Old Char Color: 104-->
			<textCharAction />
		</node>
	</group>
	<group name="paragraphSpace" colorInfoName="paragraphSpace">
		<node label="¶">
			<!--Old Char Color: 9-->
			<textCharAction />
		</node>
		<node label="□">
			<!--Old Char Color: 9-->
			<!--Note: box-->
			<textCharAction unicode="32" />
		</node>
	</group>
</alphabet>
